### ISSUE TITLE
Improve dialogue to setup hidden volumes

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#106]
Make the dialogue more verbose and make it easier and bullet proof to setup hidden volumes.

[See...](https://app.assembla.com/spaces/cryptostick/tickets/179-safe-creation-of-hidden-volumes-without-corrupting-encrypted-volume/details#)

**Comment by szszszsz** [comment]
Partly (verbosity) duplicated by https://github.com/Nitrokey/nitrokey-app/issues/72.

**Comment by jans23** [comment]
You are right.

**Comment by jans23** [comment]
Here is some feedback which implicates further improvements: https://www.nitrokey.com/forum/viewtopic.php?f=13&t=1832
