### ISSUE TITLE
Various packaging related problems

### ISSUE THREAD

**Issue by darix** [Nitrokey/nitrokey-app#11]
```mv data/icons/ubuntu-mono-light/apps/48/{nirtokey-app,nitrokey-app}.svg```

the URL field should only be used for desktop files with ```Type=Link```. This is ```Type=Application```.

```
==> nitrokey-app-0.2_drop_url_from_desktop_file.patch <==
Index: nitrokey-app-0.2/data/nitrokey-app.desktop
===================================================================
--- nitrokey-app-0.2.orig/data/nitrokey-app.desktop
+++ nitrokey-app-0.2/data/nitrokey-app.desktop
@@ -8,4 +8,3 @@ Icon=nitrokey-app
 Type=Application
 Categories=Utility;Security;Qt;
 Keywords=Nitrokey;OpenPGP;smart card;
-URL=www.nitrokey.com
```

the path in ```/etc``` is preserved for admin/user provided files.  ```/usr/lib/udev/rules.d``` is meant for package provided files.

```
==> nitrokey-app-0.2_udev_path.patch <==
Index: nitrokey-app-0.2/CMakeLists.txt
===================================================================
--- nitrokey-app-0.2.orig/CMakeLists.txt
+++ nitrokey-app-0.2/CMakeLists.txt
@@ -218,7 +218,7 @@ IF(NOT WIN32)
   # Install Nitrokey udev rules
   install(FILES
     ${CMAKE_SOURCE_DIR}/data/40-nitrokey.rules
-    DESTINATION /etc/udev/rules.d
+    DESTINATION /usr/lib/udev/rules.d
   )
 
   # Install autocompletion scripts
```

not all packages needed for building are properly enforced with "configure" checks. Things i manually "discovered" with failed builds

a) pkgconfig(libusb).

b) After adding gtk+-2.0 to the build environment, the build failed again because it tried to use libappindicator and libnotify, which weren't available. so either the #ifdef in the code are missing or the "configure" checks should fail.

openSUSE/SLES packages can be found later [here](http://software.opensuse.org/download.html?project=security&package=nitrokey-app)

**Comment by darix** [comment]
Another thing:
```
I: Program is likely to break with new gcc. Try -fno-strict-aliasing.
W: nitrokey-app strict-aliasing-punning nitrokey-app-0.2/src/response.cpp:411, 413
```

**Comment by darix** [comment]
```pkg-config --variable=udevdir udev``` could be used to query the proper system path.

**Comment by jans23** [comment]
Thanks for the feedback. Could you help and create a patch (pull request), please?

**Comment by szszszsz** [comment]
Help wanted with issues related to:

>  not all packages needed for building are properly enforced with "configure" checks. Things i manually "discovered" with failed builds
> 
> a) pkgconfig(libusb).
> 
> b) After adding gtk+-2.0 to the build environment, the build failed again because it tried to use libappindicator and libnotify, which weren't available. so either the #ifdef in the code are missing or the "configure" checks should fail.

**Comment by darix** [comment]
those 2 points are not packaging related but missing configure checks and ifdefs in the code

**Comment by szszszsz** [comment]
Hi @darix !
I have modified `CMakeLists.txt` as suggested. Could you check mentioned commits (or whole ` issue_prevent_make_install_dirty_the_root_filesystem` branch) for changes regarding these libraries?
I am not sure have I covered all cases there.
