### ISSUE TITLE
Make the Nitrokey app more secure (sig binary, provide checksums+GPG)

### ISSUE THREAD

**Issue by beerisgood** [Nitrokey/nitrokey-app#110]
The apps from https://www.nitrokey.com/download goes over HTTPS- which is good! but:
We can't verify the apps (i only check Windows).

The exe isn't signed- it even give me the window and ask if i realy want to start this app because it comes from another pc. Not realy secure!
And not only this. We can't verify the file is realy from you, because of no checksums (please add SHA512!) and GPG file.

Please fix this

**Comment by beerisgood** [comment]
*Push*

See also https://github.com/Nitrokey/nitrokey-app/issues/136

**Comment by szszszsz** [comment]
Hi! This is on our to-do list. Will be done as soon as possible. Please feel free to 'bump/push' in case this would appear forgotten.

**Comment by davesteele** [comment]
In addition, a signature of the source tar file would be [automatically checked](https://wiki.debian.org/debian/watch#Cryptographic_signature_verification) by the deb update process.

**Comment by sedrubal** [comment]
And it would be nice if you'd sign your commits: https://mikegerwitz.com/papers/git-horror-story

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
Cmon guys, this issue is now 6 months old without any change.
I think Nitrokey stands for security? if i see this, then i dont think so.

**Comment by sedrubal** [comment]
Thanks @szszszsz for signing (at least most of) your commits 😉 👍

**Comment by beerisgood** [comment]
another month...
*bump*

**Comment by beerisgood** [comment]
I see you pin that to milestone 1.0
Hope you get that finish soon.

**Comment by beerisgood** [comment]
80% complete
Did you know how long it takes to finish it?

**Comment by szszszsz** [comment]
Hi!
A signed binary for Nitrokey App v1.0 is available at [release page](https://github.com/Nitrokey/nitrokey-app/releases). There were reported issue though regarding device detection on some Windows boxes. A fix will be released today for this.
Regarding your first comment, @beerisgood, the Windows Smart Screen will still show up until binary will get enough 'reputation' in cloud. However this time on the screen instead of `Unknown publisher` the `Nitrokey` should show up. In binaries properties (in separate tab) one can check signing status - I have tested it will be invalid on file modification. Would you like to have sha512 signed by GPG nevertheless?

**Comment by szszszsz** [comment]
@sedrubal The other unsigned commits from that time came from using automatic merging offered by Github. I have changed the workflow with merging the changes locally, thus no unsigned commits should be present from my side.

**Comment by szszszsz** [comment]
@davesteele I am not sure I understand when GPG signature will be validated, but I hope to investigate this further. Do you have more materials explaining this?

**Comment by davesteele** [comment]
Debian packaging includes a '[watch](https://www.debian.org/doc/manuals/maint-guide/dother.en.html#watch)' file, which provides a set of rules for finding and parsing upstream source tars. The [uscan(1)](https://manpages.debian.org/jessie/devscripts/uscan.1.en.html) utility parses that file to download the source tar, or to determine the most recent version.

uscan/watch can support [finding and verifying a signature](https://wiki.debian.org/debian/watch#Cryptographic_signature_verification) during the download process. For a project on GitHub, the easiest way for you to support this is to add the signature file to the set of files in a 'release'. It helps if the path to the signature is &lt;tgz url&gt;.asc.

**Comment by beerisgood** [comment]
@szszszsz to valid a GPG you need other guys which validate it, upload that with their own key to the server and then you will see that under your key.
I validate your GPG sig with my own GPG sig:
`Key ID: 97F9E213620F071D`

I also miss a nitrokey-app-v1.1.exe.asc GPG file to verify the binary, as well as checksums for the binary

**Comment by szszszsz** [comment]
@beerisgood Indeed! Thank you for signing the key. Should not you sent it to me for import and publish though?

As for .asc and checksums - these seems redundant in the presence of the code-signing certificate, but in case someone wants to validate using other tools I have uploaded them too into [release](https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.1) files.

**Comment by szszszsz** [comment]
@davesteele I will move that to separate issue for easier tracking.

**Comment by szszszsz** [comment]
Initial issue fixed, closing.

**Comment by beerisgood** [comment]
@szszszsz: Why should i upload my key? I upload it to the GPG server
Anyone can download the public key
