### ISSUE TITLE
Provide binaries for Ubuntu via Launchpad

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#115]

**Comment by szszszsz** [comment]
Waiting for confirmation.

**Comment by szszszsz** [comment]
Today first packages should be available under https://code.launchpad.net/~szszszsz/+recipe/nitrokey-daily-testing
After checking solution will be moved to official site: https://code.launchpad.net/~szszszsz/+recipe/nitrokey-daily
Additionally `release` channel with packages from `release` repository branch is planned to be added.

**Comment by szszszsz** [comment]
Packages for 0.5 are available under:
- ppa:szszszsz/ppa
- directly: https://code.launchpad.net/~szszszsz/+archive/ubuntu/ppa/+build/10963577
- directly: https://code.launchpad.net/~szszszsz/+archive/ubuntu/ppa/+build/10963578
In near future these will be moved to official PPA.

**Comment by szszszsz** [comment]
Snapcraft package is available in Snappy's store. To install please execute:
```
sudo snap install nitrokey-app --devmode
```

**Comment by szszszsz** [comment]
Official PPA:
https://launchpad.net/~nitrokey-team/+archive/ubuntu/ppa
