### ISSUE TITLE
Admin PIN with more than 20 chars

### ISSUE THREAD

**Issue by gimbar** [Nitrokey/nitrokey-app#12]
I tried to use an admin-PIN with more than 20 chars. The ui throw away any char more than 20 without any visual indication. Afterwards I tried to unlock my Nitrokey with the full length PIN. In this dialog I was able to type it in completely and didn't match. After 3 tries I had to reset it.

**Comment by jans23** [comment]
Thank you for the bug report. That should be fixed.
For your information: It's not necessary to use a PIN longer than 6 or 8 characters because that is sufficient for 3 tries. A PIN differs to a password by not allowing brute force attacks.

**Comment by indolering** [comment]
You should include a link to some documentation on the subject, if not have a wizard that walks you through the setup process and explains everything to the user.

**Comment by szszszsz** [comment]
--> Edit control in 'Enter PIN Dialog' should not accept more than maximum length (currently 20) chars. 
Similar with issue #15.

**Comment by szszszsz** [comment]
Done
