### ISSUE TITLE
QAction file not found. Missing QT widgets in QT5

### ISSUE THREAD

**Issue by cornelinux** [Nitrokey/nitrokey-app#121]
The make process will fail on ubuntu 14.04 with Qt5.

With Qt 5 I need to add "widgets" to the .pro file:

    QT       += core gui widgets

Otherwise I get 'QtGui/QAction' file not found.

**Comment by szszszsz** [comment]
Hi @cornelinux !
Could you check what exact version of Qt5 is available on your OS (`apt show qt5-default` or similar for other package name)?
Actually we build each commit/PR on 14.04 on Travis service with unofficial Qt 5.5.1. You can check current Travis configuration here: [config](https://github.com/Nitrokey/nitrokey-app/blob/master/.travis.yml) .
 I will check if your suggested change is transparent for 16.04 on the next occasion and merge.

**Comment by cornelinux** [comment]
Hi @szszszsz 
I am the worst issue reporter, ever. I am sorry this.
Due to other requiremts I upgraded my system to 16.04...

:-/ everything compiles fine now, with cmake.

I am sorry, that we can not provide a real good solution here. But I guess my 14.04 was very dynamically grown... and it might be difficult to reproduce now.

**Comment by szszszsz** [comment]
Hi @cornelinux !
We can take a lesson from each issue reported :-) At the very least if something is unclear, it is a sign we should add proper information to Readme file.
Last time I have checked it seems that Qt5 latest versions (5.5+) are not officially supported on 14.04 thus some issues may arise on it. The official package for 14.04 is 5.2.x.
