### ISSUE TITLE
Notification Window after initialization

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#130]
After successful initialization of a new device (generation AES keys and writing of random data to storage) the user should be asked to disconnect and reconnect his Nitrokey Storage. Perhaps this notification could be added to the "success"-window.

**Comment by szszszsz** [comment]
Please provide translation for:
`Storage successfully initialized with random data. Please remove the device and insert again to complete initialization process.`

**Comment by jans23** [comment]
The translation is: "Der Speicher wurde erfolgreich mit Zufallsdaten
initialisiert. Um die Initialisierung abzuschließen, entfernen Sie das
Gerät und verbinden Sie es bitte erneut."

>
