### ISSUE TITLE
Debian Jessie:  Nitrokey-app "active" but no GUI

### ISSUE THREAD

**Issue by Dowwie** [Nitrokey/nitrokey-app#140]
Setup:  Debian 8 (jessie) and gnome desktop

I installed the amd64 nitrokey-app debian package as root (nitrokey-app_0.4_Debian-8-jessie_amd64.deb)

With a nitrokey inserted into a usb port, I run nitrokey-app.  Gnome displays in the upper left of the screen that nitrokey-app is active, yet no GUI manifests nor does an icon appear in the taskbar.

Note that I've already:
- installed the Qt libraries
- added udev rule 40-nitrokey.rules to /etc/udev/rules.d

**Comment by szszszsz** [comment]
Hi!
If possible please check with Qt libraries in version 5.4.2+ and update #86.
This is a duplicate of https://github.com/Nitrokey/nitrokey-app/issues/86

**Comment by szszszsz** [comment]
Hi! Regarding running Nitrokey App on Debian - you might be interested in a list of working WMs I have just compiled: https://github.com/Nitrokey/nitrokey-app/wiki/Working-WMs-on-Debian-Jessie-8.6
