### ISSUE TITLE
Specify min/max pin length in UI

### ISSUE THREAD

**Issue by indolering** [Nitrokey/nitrokey-app#15]
The current UI only states the character class allowed, it does not specify a min/max length.

**Comment by indolering** [comment]
Ahh, I see it gives a warning if it's too long.  Still, it would be nice to see it in the dialog box itself.

**Comment by jans23** [comment]
I suggest to add the following text to the dialog: "PINs can only be tried three times and are secure against brute force guessing. A PIN of 6 or 8 digits is sufficiently long and longer or more complex PINs are usually unnecessary."

**Comment by szszszsz** [comment]
Fixed password change form as mentioned.
