### ISSUE TITLE
Sign using Apple's Binary Signing

### ISSUE THREAD

**Issue by indolering** [Nitrokey/nitrokey-app#16]
The current app is not signed with Apple's binary signing system, requiring the user to alter a system configuration setting and right-click when they open the app for the first time.  A signing key from Apple only costs $100.

**Comment by szszszsz** [comment]
Both signed and unsigned binaries are now provided for v1.0 release. 
https://github.com/Nitrokey/nitrokey-app/releases
Closing as done.
