### ISSUE TITLE
segmentation fault when trying to unlock password save

### ISSUE THREAD

**Issue by zem** [Nitrokey/nitrokey-app#161]
Hi, 

Just trying out the app, I installed the debian package from the nitrokey homepage: 
nitrokey-app_0.4_Debian-8-jessie_amd64.deb

The application segfaults when  I unlock the password store. 
The last thing I did was to set a test TOTP and set the "require password for OTP" setting to true. 

It shows my otp under passwords. Before I did the OTP setting, my regular passwords where shown in the same menu. 

regards 

    Hans

**Comment by szszszsz** [comment]
Hi Hans,

Thank you for contributing by reporting this issue!
1. Which version of Debian are you using? I guess it matches the system and bits (Debian 8 x64) but just wanted to confirm.
2. We have just finished v0.5 of the App and are releasing packages one by one. I hope to make Debian package available this week. It is possible this issue is fixed in latest version. The code was rewritten in the most used parts thus App should be more stable.
3. Could you share how have you handled #86 ?

Best!

**Comment by zem** [comment]
Hi, 

On Mon, Oct 03, 2016 at 12:29:31AM -0700, szszszsz wrote:
> Thank you for contributing by reporting this issue!

> 1. Which version of Debian are you using? I guess it matches the system and
> bits (Debian 8 x64) but just wanted to confirm.

It is Debian Unstable. x64 architecture. 


> 2. We have just finished v0.5 of the App and are releasing packages one by
> one. I hope to make Debian package available this week. 
> It is possible this issue is fixed in latest version. The code was rewritten
> in the most used parts thus App should be more stable.

I will test it for sure. 


> 3. Could you share how have you handled #86 ?

I am using wmii-hg with its own tray, worked out of the box. 

regards 

    Hans 

-- 
This final error message indicates a successful installation of a 
UNIX GIS cluster node.
This is not an error, as the misleading message may suggest.
(found at Sterling Commerce Knowledgebase)

**Comment by szszszsz** [comment]
The package for Debian is released - please check [download](https://www.nitrokey.com/download) page and share your feeling about its stability.
I see. I thought you are using Debian Jessie which has old (`5.3`) Qt libraries thus improperly handles tray icon unfortunately. Stretch/Sid should support it on all WM's since it uses `5.6+`.

**Comment by szszszsz** [comment]
Hi Hans!
Did you get a chance to test latest Debian package?

**Comment by zem** [comment]
Hi, 

not yet, I hope to have a chance later that weekend. 

regards 



On Sat, Oct 08, 2016 at 02:38:19AM -0700, szszszsz wrote:
> Hi Hans!
> Did you get a chance to test latest Debian package?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Nitrokey/nitrokey-app/issues/161#issuecomment-252415007

-- 
This final error message indicates a successful installation of a 
UNIX GIS cluster node.
This is not an error, as the misleading message may suggest.
(found at Sterling Commerce Knowledgebase)

**Comment by zem** [comment]
Hi, 

I did test the new package, it is working perfectly. Many thanks! 

regards 

   Hans 

On Sat, Oct 08, 2016 at 02:38:19AM -0700, szszszsz wrote:
> Hi Hans!
> Did you get a chance to test latest Debian package?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Nitrokey/nitrokey-app/issues/161#issuecomment-252415007

-- 
This final error message indicates a successful installation of a 
UNIX GIS cluster node.
This is not an error, as the misleading message may suggest.
(found at Sterling Commerce Knowledgebase)

**Comment by szszszsz** [comment]
Hi!
That is great! Nevertheless if you will manage to crash it please let us know :-)
Happy using!

**Comment by szszszsz** [comment]
@zem Forgot to mention we have just released 0.5.1 :-) Package should be available in a day or two.

Maintenance note: closing as invalid since issue has occurred on older version and after retest on latest (probably 0.5) its gone.
