### ISSUE TITLE
Mac OS X version and missing QT libraries

### ISSUE THREAD

**Issue by ykram** [Nitrokey/nitrokey-app#163]
The binary for the nitrokey-app on OS X references a few QT libraries that aren't installed when the app is downloaded via the nitrokey website in binary form. Anytime a user clicks the app in Applications, nothing happens as a result. The fix/workaround in this case was to download the QT library and then fix the linked dylib's manually using install_name_tool.

My understanding of the QT licensing model is that QT requires a paid license for statically compiled binaries using QT, however it might be beneficial to package the QT libraries with the app or offer additional instructions on the website regarding the need for QT libraries and how to install them.

**Comment by szszszsz** [comment]
Hi! We are working on this issue. I will let you know when new package is released.
Similar problem on the forum: https://www.nitrokey.com/forum/viewtopic.php?f=13&t=1779

**Comment by jans23** [comment]
We just released 0.5.1. Please download and see if the issue still happens.
