### ISSUE TITLE
Invisible tray icon on openSUSE Tumbleweed unless run as root 

### ISSUE THREAD

**Issue by heikojansen** [Nitrokey/nitrokey-app#176]
I know there have been a few issues concerning this issue or variations thereof but I could not find out what the ultimate cause and fix are.
The Readme says that this issue (or one that looks like it) can be fixed on Debian Jessy by updating Qt to version 5.4.2 or up but I already have Qt 5.7.0 and still experience the issue.

I´m using a Nitrokey Storage and v0.5.1 of the app with openSUSE Tumbleweed x86_64, Qt 5.7.0, plasma 5.8.0, frameworks 5.26, apps 16.08.
sni-qt is installed.
Is does not make a difference if appmenu-qt and appmenu-qt5 packages are installed or not.

If I have the nitrokey-app started automatically on login or try to start it manually the program seems to run but no icon is shown in the tray. Insertion and removal of a Nitrokey is detected (pop-up messages are shown), but I cannot see the app to use the Nitrokey.

Manually starting the app in the shell shows these messages repeatedly:

```
jansen@mtron:~> nitrokey-app 
Application started successfully.

(process:3774): Gtk-CRITICAL **: IA__gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:3774): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:3774): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:3774): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(process:3774): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:3774): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:3774): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:3774): Gtk-CRITICAL **: IA__gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:3774): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
```

Looking at the section "Entries" ("Einträge") of the system tray settings ("Einstellungen für Systemabschnitt der Kontrolleiste"), an entry for the nitrokey-app appears / disappears when it is started / stopped, but there is no textual description for that entry.

If I start the app as root the icon does appear in the tray and there are no GTK/GLib error messages in the shell:

```
mtron:~> nitrokey-app 
Application started successfully.
```

I can then use the tray icon to access my nitrokey.

I´m sure that things worked fine a few weeks ago when I received my nitrokey (as kickstarter backer) with v0.2 of the app and the openSUSE Tumbleweed state of that time.

In the weeks since then I did not have time to use the nitrokey so I do not know when things started to go wrong.
I hoped that updating the app to the latest release would fix the problems, but it did not (in order to test that assumption I first had to create an openSUSE build service account and build the newest version myself - will submit the changes back to the "security" obs project later today...).

**Comment by szszszsz** [comment]
Hi! Error messages suggest package is built with libappindicator(cmake is
configured to do this currently). Your report regarding app's working with
or without appmenu-qt seems to confirm this. Could you build app from
source using `qmake && make` commands and check?

15.10.2016 16:19 "Heiko Jansen" <notifications@github.com> napisał(a):

**Comment by heikojansen** [comment]
I currently do not have a build env available, but if I unconditionally add "-DHAVE_LIBAPPINDICATOR=NO" to the cmake command in the OBS project and install the resulting package, starting and using the app as non-root (and also as root) works fine!

I just checked: libappindicator and libnotify are available on my computer as the versions from the official Tumbleweed repos (so the same that is used in OBS to build nitrokey-app against).

**Comment by heikojansen** [comment]
The idea of "see if it works if started by root" was inspired by some other issue report but thinking about it some more made me realize that the different behavior is in fact not connected to the "root" user id.
The tray icon also works fine if I simply "su - ..." to any other user id in my shell and start the nitrokey-app from there. So this is probably about some environment variable not set or set differently there than for the currently logged-in KDE user. I´ll see if I can find out which one it is...

**Comment by heikojansen** [comment]
Looks like XDG_CURRENT_DESKTOP is in control here. By default it is set to "KDE" and with that value the icon is invisible and we get the bunch of error messages in the shell when starting nitrokey-app.
If I simply ```unset XDG_CURRENT_DESKTOP``` that env var I can start nitrokey-app without error messages and the icon shows up in the pop-up list of icons of the system tray (which is triggered by clicking on the arrow symbol in the control panel).
If I set XDG_CURRENT_DESKTOP to some other arbitrary value and start the app also no error messages appear and the nitrokey icon is immediately visible in the control panel (instead of the secondary pop-up list).
Hope that helps...

**Comment by szszszsz** [comment]
Thank you for checking that! `libappindicator` library is not required for application to work, rather to support where Qt library is not sufficient to show tray icon. If it works without it then it is even better. If possible please use the app without it.
Currently only on Debian 8 there are problems with tray icon on Gnome and XFCE WMs.
I have checked your findings with `XDG_CURRENT_DESKTOP` there (by settings different values) but unfortunately it has not helped, whether application was compiled with `libappindicator` or not. Nevertheless I will check that direction once more on next occasion.

**Comment by heikojansen** [comment]
As far as I can see, the "Download" section on nitrokey.com links to this package at least for SuSE: https://build.opensuse.org/package/show/security/nitrokey-app

That package currently offers v0.2 of nitrokey-app. That´s why I created a derived package to update to v0.5.1 and submit the necessary changes to the base package:
https://build.opensuse.org/package/show/home:der_rabe/nitrokey-app

If you can tell me on which OS / platform the app should be compiled with ```libappindicator``` I can update the package spec and submit the changes back to the "security" project.
If you think that in order to build the package ```qmake``` should be used instead of ```cmake``` I can try to change that, too. (I had to apply some patches to ```CMakeLists.txt``` to successfully build the package anyway.)

**Comment by szszszsz** [comment]
That would be great! 
Actually I am considering dropping `libappindicator` support since current OSes / platforms have latest Qt libraries. Please globally disable it for now.
We use `qmake` to build app on Ubuntu and Debian. `CMake` works too, so it should be fine to leaving this as is. And you have already checked this method.

**Comment by heikojansen** [comment]
The submit request to update the package to v0.5.1 (incl. the removal of libappindicator usage) has been accepted: cf. https://build.opensuse.org/package/show/security/nitrokey-app

**Comment by szszszsz** [comment]
Great! For a final check: could you please check will package install from official repository and run properly? If yes please close the issue. Thank you!

**Comment by heikojansen** [comment]
Tested successfully on openSUSE 42.1 and Tumbleweed.
