### ISSUE TITLE
RPM Package conflicts with system packages

### ISSUE THREAD

**Issue by Daemoen** [Nitrokey/nitrokey-app#18]
Error: Transaction check error:
  file /etc/bash_completion.d from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package filesystem-3.2-32.fc22.x86_64
  file /usr/share/applications from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package filesystem-3.2-32.fc22.x86_64
  file /usr/share/locale from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package filesystem-3.2-32.fc22.x86_64
  file /usr/share/locale/de_DE from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package filesystem-3.2-32.fc22.x86_64
  file /usr/share/locale/de_DE/LC_MESSAGES from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package filesystem-3.2-32.fc22.x86_64
  file /usr/share/pixmaps from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package filesystem-3.2-32.fc22.x86_64
  file /etc/bash_completion.d from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package lldpad-0.9.46-8.git48a5f38.fc22.x86_64
  file /etc/bash_completion.d from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package fcoe-utils-1.0.29-7.git9267509.fc22.x86_64
  file /etc/bash_completion.d from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package bash-completion-1:2.1-7.20150513git1950590.fc22.noarch
  file /etc/bash_completion.d from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package udisks-1.0.5-2.fc22.x86_64
  file /etc/bash_completion.d from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package yum-utils-1.1.31-508.fc22.noarch
  file /etc/udev from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package systemd-219-25.fc22.x86_64
  file /etc/udev/rules.d from install of nitrokey-app-0.2-1.x86_64 conflicts with file from package systemd-219-25.fc22.x86_64

None of these errors should arise in a properly packages rpm in the first place.  It's kind of scary that this package is conflicting with system level files and directories.

**Comment by msgctl** [comment]
Fixed, please re-test: https://github.com/Nitrokey/nitrokey-app/tree/rpm_collision_fix

CPack, which this project uses to build its RPMs, was generating directories already provided by package dependencies.

**Comment by szszszsz** [comment]
Hi @Daemoen !
I have merged msgctl changes into master. Please reopen if issue still occurs.

To build package please run:
> cmake .
> make package
