### ISSUE TITLE
GTK3 support

### ISSUE THREAD

**Issue by ignatenkobrain** [Nitrokey/nitrokey-app#187]
would be nice to move away from gtk2 as it's obsoleted. I didn't have time to check how much effort it would take..

**Comment by szszszsz** [comment]
Hi!
Nitrokey App is based on Qt5. I guess you mean the tray icon support - it will be removed in next versions as Qt issues with tray are now fixed.

**Comment by ignatenkobrain** [comment]
ah, ice to hear this.
