### ISSUE TITLE
automatic detection for bash_completion directory

### ISSUE THREAD

**Issue by ignatenkobrain** [Nitrokey/nitrokey-app#189]
Ideal way is to use pkg-config:
```
$ pkg-config --variable=completionsdir bash-completion
/usr/share/bash-completion/completions
```

Given that it needs some additional package in buildroot I would check for that pkgconfig, and if it doesn't exist, then fallback to `/etc/bash_completion.d` or even new-style (/etc is for configs, not for real tools).

**Comment by ignatenkobrain** [comment]
and definitely give users way to override it after all

**Comment by nkoehring** [comment]
Good start to enable people to override the bash-completion path would be to change the CMakeLists.txt entry to a relative path (like `etc/bash-completion.d` instead of `/etc/bash-completion.d`), so that at least a PREFIX works.

**Comment by szszszsz** [comment]
Bash completion and udev rules dir are now detected during CMake configuration. Their absolute path is stripped from initial slash `/`, so the prefix could work.
