### ISSUE TITLE
No SRC Rpm or RPM Spec File

### ISSUE THREAD

**Issue by Daemoen** [Nitrokey/nitrokey-app#19]
Given that the nitrokey-app has a public github that accepts pull requests, the spec file for building the linux rpm should be included in the repo.

Pertains to issue #18

**Comment by jans23** [comment]
It should be relatively easy to get the spec file from the [source rpm](http://download.opensuse.org/repositories/security/openSUSE_13.2/src/nitrokey-app-0.2-2.1.src.rpm) and potentially update it. Could you help and develop a patch?

**Comment by msgctl** [comment]
@Daemoen This project uses CPack to generate RPM spec. Refer to #18
