### ISSUE TITLE
Update installation instructions for Fedora

### ISSUE THREAD

**Issue by ignatenkobrain** [Nitrokey/nitrokey-app#192]
```
sudo dnf install nitrokey-app
```

Today I built nitrokey-app in Fedora (http://koji.fedoraproject.org/koji/packageinfo?packageID=23317), so it should be available in:
* F24, F25 -- 1-3 days (updates-testing), 7-8 days after previous step (stable)
* F26 (Rawhide) -- 1-3 days

**Comment by szszszsz** [comment]
@jans23 Should be added probably to site's download section

**Comment by Germano0** [comment]
It's all right at page [https://www.nitrokey.com/download/fedora](https://www.nitrokey.com/download/fedora)

**Comment by szszszsz** [comment]
Indeed, have not looked there for some time. Thank you!
