### ISSUE TITLE
OTP secret field's max length changes only with text inside

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#195]
Secret field's max length is changing only when any text exists in it. It should change nevertheless.

**Comment by jans23** [comment]
I thought the length is fixed. So how does it change at all? Please
elaborate. 

>

**Comment by szszszsz** [comment]
It is a UI input field attribute for OTP secret. It's maximum length was changing depending on whether it was base32 (32) or hex (40) selected. However it was not when input field was empty thus with scenario, where user directly inputs hex secret input was limited incorrectly to 32 characters (while should be 40).

**Comment by jans23** [comment]
Ok. Thanks for the explanation.

>

**Comment by szszszsz** [comment]
Fix will be merged along with the support for Pro 0.8
