### ISSUE TITLE
Add command line parameter to force language

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#199]
Add `--language` CLI parameter for cases where automatic language detection would not return expected results (eg. where user has different language/locale on OS than he wants to use in application).

**Comment by jans23** [comment]
What are the available options/languages?

**Comment by szszszsz** [comment]
Available options are listed in `i18n/`directory - all ts/qm pairs without the `nitrokey_` prefix. Currently these are:
- none - translation file will be selected automatically (default)
- arabic - recently added translation for Arabic (should be selected automatically on systems with Arabic locale set)
- de_DE - German
- en - English (second default if there could be no language file selected automatically)

Translation files are selected automatically through locale code (like de_DE, en_GB etc.) or by language. If OS has locale other than language user wants to use, he has to run application once with desired language, eg.:
`nitrokey-app.exe --language arabic`
The choice will be stored in application's settings file. To clear it user has to use `--language` switch without a param:
`nitrokey-app.exe --language`
Similar information regarding language switching could be obtained by running:
`nitrokey-app.exe --help`
