### ISSUE TITLE
Storage: verify Update PIN when "enable firmware update" is selected

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#2]
cryptostick->stick20NewUpdatePassword ((uint8_t *)OLD,(uint8_t *)NEW);

**Comment by jans23** [comment]
When I select Activate Firmware Update the App prompt for the Admin PIN. Instead it should prompt for the Firmware Password.

**Comment by szszszsz** [comment]
Changed as in comment.
