### ISSUE TITLE
Vector Icon

### ISSUE THREAD

**Issue by indolering** [Nitrokey/nitrokey-app#20]
The icon on OS X is very low resolution.  This is what it looks like when I open it from the applications folder:

![nitrokey-screenshot](https://cloud.githubusercontent.com/assets/44454/11023661/a4706680-863c-11e5-9cd9-5f7a5402802e.png)

**Comment by szszszsz** [comment]
I have updated the icon in v1.0 package:
![issue_20](https://cloud.githubusercontent.com/assets/17005426/25526091/49be414e-2c12-11e7-8656-46a9a21be7c7.PNG)
Issue will be closed on merge.
