### ISSUE TITLE
nitrokey-app keeps asking for admin PIN when trying to configure TOTP or HOTP slot

### ISSUE THREAD

**Issue by meekstone** [Nitrokey/nitrokey-app#211]
I cannot configure OTP on my Nitrokey Pro. I am using Debian Jessie with nitrokey-app 0.6.1.

Steps I have taken when trying to configure an OTP slot:

1. Start nitrokey-app
2. Connect Nitrokey Pro to USB port
3. Click on nitrokey-app tray icon and choose "Configure" -> "OTP and Password safe"
4. Enter admin PIN
5. On the tab "OTP Slot Configuration": choose "TOTP", "TOTP slot 1", set "testing" as name
6. On the tab "OTP Slot Configuration": click "Generate random secret"
7. On the tab "OTP Slot Configuration": click "Save"
8. Enter admin PIN

At this point, I expect nitrokey-app to save the entered configuration into TOTP slot 1. What happens instead is that nitrokey-app keeps asking for the admin PIN over and over again. It does not matter whether I enter the correct admin PIN or press "Cancel" in the "Enter admin PIN" dialogue. The dialogue will just pop up again. The entered configuration is never written to the Nitrokey Pro. The only way to stop this is to kill nitrokey-app or remove the Nitrokey Pro from the USB port.

I have also tested configuring TOTP slots 4 and 9 as well as HOTP slot 1. The behaviour is as described above.

(I can successfully configure the password safe and store passwords.)

Any hint is appreciated.

**Comment by szszszsz** [comment]
Note: not reproducible on Ubuntu 16.10 with Pro 0.7 and 0.8, v0.6.1

**Comment by szszszsz** [comment]
Hi! Thank you for report!
Could you run the app in debug mode and get logs? Here are the steps:
1. Run `nitrokey-app --debug`
2. Execute scenario with issue
3. Enter debug window through tray icon (`Debug` list item)
4. Copy window content and save it to file
5. Attach the file to the new comment

Your description might show some issues with communication to device. Debug log should confirm it.
In the meantime I will check why `Cancel` button has not worked to break the loop.

**Comment by meekstone** [comment]
The problem always occurs.
I attached the debug log. Please note that I had to disconnect the Nitrokey Pro during the "asking for PIN" loop in order to open the debug window.
[Nitrokey_Debug.txt](https://github.com/Nitrokey/nitrokey-app/files/683062/Nitrokey_Debug.txt)

**Comment by szszszsz** [comment]
Thank you for debug log. Could you attach also `dmesg` output?
It seems that device has some connection issues for some reason.

**Comment by meekstone** [comment]
Which dmesg lines do you need? Just the lines printed when connecting the device? Or all lines printed during an OTP configuration attempt?

**Comment by szszszsz** [comment]
Most helpful would be all messages printed while device is connected including inserting and removing it from USB port.

**Comment by szszszsz** [comment]
Could you check please also the firmware version in `About` window?

**Comment by meekstone** [comment]
Firmware version is 0.8. (App version is displayed as 0.5.1 but I definitely installed version 0.6.1 from your website, 'dpkg -l nitrokey-app' confirms this.)
The attached Nitrokey_dmesg.txt contains the dmesg output generated when

1. Connecting the Nitrokey Pro
2. Trying to configure a TOTP slot
3. Disconnecting the Nitrokey Pro to break the "asking for PIN" loop

[Nitrokey_dmesg.txt](https://github.com/Nitrokey/nitrokey-app/files/683192/Nitrokey_dmesg.txt)

**Comment by szszszsz** [comment]
Thank you for the logs! It should be fixed within 48 hours.

**Comment by meekstone** [comment]
I can confirm that TOTP and HOTP configuration is working on Debian Jessie with nitrokey-app version 0.6.2. Thank you for fixing this so fast.

**Comment by szszszsz** [comment]
You are welcome!
