### ISSUE TITLE
Segfault on reconnecting device

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#229]
>i manage to segfault after connecting/disconnecting the pen multiple time

Details: https://github.com/Nitrokey/nitrokey-app/issues/227#issuecomment-288894855
v: 1.0-beta.1

**Comment by MauroMombelli** [comment]
possible explanation: scdaemon was not running (manually killed)

**Comment by szszszsz** [comment]
Issue has not occurred during retesting on Windows 8.1 with `nitrokey-app-v1.0-beta.1`. 
Originally reported on ArchLinux - will be retested on Ubuntu 16.10.

**Comment by szszszsz** [comment]
Have not retested yet, but @MauroMombelli - do you have any effective failure scenario for this issue? Just to make sure I will retest it in same place you have found it.

**Comment by szszszsz** [comment]
Issue not spotted yet during day-to-day use. Under observation.

**Comment by MauroMombelli** [comment]
Now that I have updated the keys I thing I'm gonna experiment a bit more
during weekend.

**Comment by szszszsz** [comment]
Not reproduced. Please reopen when it will occur on latest version.
Adding `invalid` label since nothing has changed in code.
