### ISSUE TITLE
Refocus App on OS X

### ISSUE THREAD

**Issue by indolering** [Nitrokey/nitrokey-app#23]
When the config screen is already open, reopening it through the menu applet does not bring the screen into focus.  You must manually dig through open windows to find it.

**Comment by ChristianBagley** [comment]
Agreed, this was the first thing I noticed when I began using the app. And although it isn't a huge concern, it has become rather frustrating.

**Comment by szszszsz** [comment]
Issue reproduced on Ubuntu 15.04 and fixed. Please check on Mac with latest commit and reopen if needed.
