### ISSUE TITLE
Invalid feedback on changing admin PIN

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#230]
> i manage to [...] changing the admin pin work but give no feedback, like the "ok" button does not work
edit: the pin was NOT changed, the new pin was too short. I got confused because also the main app return a "pin invalid" without telling you if the old or new pin is invalid!

Details: https://github.com/Nitrokey/nitrokey-app/issues/227#issuecomment-288894855
v: 1.0-beta.1

**Comment by MauroMombelli** [comment]
correction: the operation didn't work, because the new pin was too short.
