### ISSUE TITLE
UI/image Tray icon is not always visible

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#232]
Usually the application icon is not visible while being in `tray dock`. Possibly change the colour from silver to more contrasting one or add a contrasting element.

**Comment by milouse** [comment]
Maybe just add a preference option, which allow one to choose/change the tray icon family ? You already provide two different variant we could pick : https://github.com/Nitrokey/nitrokey-app/tree/master/data/icons

**Comment by alex-nitrokey** [comment]
Hi, I am not sure if this is really about contrast. I've seen this "invisibility" of the icon from time to time. Right now the icon is never seen with 1.2.1 on LXDE.

Light background, invisible icon (not light, invisible):
![screenshot_20180319_084206](https://user-images.githubusercontent.com/36155797/37583504-f19c1a3c-2b51-11e8-82e5-873a923377a8.png)

Same on dark background (closing and reopening App):
![screenshot_20180319_084245](https://user-images.githubusercontent.com/36155797/37583513-fb62901e-2b51-11e8-9a56-299492ae47aa.png)

Going back to light background (without closing and reopening):
![screenshot_20180319_084320](https://user-images.githubusercontent.com/36155797/37583525-05aa5cb4-2b52-11e8-9c13-6590f2547a6b.png)

Using the same OS (Arch Linux) and the same App version on my private system with LXQT does not provoke this behaviour at all (dark and not light background by default though).

Never realized this issue on another system yet, and I tried a lot :blush: @milouse this is why I reported in AUR and not here btw.

**Comment by alex-nitrokey** [comment]
Well... or it is something totally different :thinking: I tried LXQT on this system now. At first there was no icon at all as well, after choosing a general iconset this "executable" icon was appearing (the purple on).
![screenshot_20180319_085714](https://user-images.githubusercontent.com/36155797/37583944-db5b4b7e-2b53-11e8-88a6-abeb0a2ccce5.png)
Mh, let's see if I can figure this out. As some system icons are not visible as well and as the icon is visible on a different device with same OS, DE and App version I consider this a special config error on my side...

**Comment by techge** [comment]
#346 fixes the icon problem on my private machine. Will try if it still persists on the other one and report here (probably thursday...).

**Comment by alex-nitrokey** [comment]
Works like a charm on the original mentioned machine. So this is fixed on my side.
@szszszsz dunno if your original post is still of interest?!

**Comment by anthraxx** [comment]
@szszszsz well i face the non visibility issue as well hence i leave a comment here. The default non-connected tray icon is pure black which makes it fully invisible for my regular theme, which is a plain black traybar.
Works fine if i switch for testing to a white traybar, maybe it should just have shades/gradient which would make it always visible. Or simply provide a configuration option to choose from would solve this as well.
PS: running on Arch Linux to icons itself work well
