### ISSUE TITLE
Setting TOTP secret with Paypal is not working

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#239]
Secret is truncated on Paypal's side. Oddly, the last HEX digit is removed in the form.
App v1.0-beta.3, Windows
Details: https://github.com/Nitrokey/nitrokey-app/issues/9#issuecomment-294583238
Reporter: @heikofolkerts
Quote:
>  When trying to use the nitrokey to register a TOTP slot for paypal I crashed the nitrokey by A) Generating a random secret in a new topt slot. Important the input format must be set to base32 at this point. B) Opening the paypal form to activate a security key – which is accessible when cancelling the registration of a mobile phone number. That form only accepts a quite short serialnumber – which I expect tob e the „secret“ that syncs both parts. C) When copying the secret generated by the nitrokey app tot he paypal form it gets truncated. So I copy nust that part back into the app. D) When saving the konfiguration the app crashes I suspect due tot he cut secret. When doing the same using the hex format and removing the last accepted digit so that it results in an secret with a odd number of digits the configuration can be saved. But the swync with paypal isn’t successful with paypal when using two six digits codes. But this may be due tot he limitation from paypal.

**Comment by szszszsz** [comment]
@techge Any chance you could get paypal's TOTP secret example?

**Comment by techge** [comment]
Mh, is it possible that paypal does not support TOTP anymore or atleast not for every region? I could only activate (another) mobile number for 2fa...

**Comment by Chris-Schaefer-DE** [comment]
FYI: 
trIed and tested today, 
TOTP did not work for me today with PayPal, verification fails (Base32, key generated by PayPal)
Google authenticator setup did work (same day)
Nitrokey app: 1.4.0, NitrokeyPro FW 0.8

**Comment by szszszsz** [comment]
@Chris-Schaefer-DE Thank you for reporting. We do test our devices with the test vectors (and cross-check with other library), so given that I would expect there are other causes like:
- wrong TOTP period window was selected;
- host PC time not synchronized (the difference should be less than couple of seconds with the time server in the internet);
- secret key was malformed during the transport (browser->application), malformed by the App itself in its input field, or wrong type of the key was selected;
- size of the secret key was too big (v0.8 should support up to 320 bits / 40 bytes);

Could you confirm please these are correctly set?


@alex-nitrokey Could you try to reproduce?

**Comment by alex-nitrokey** [comment]
Can not confirm. Tested and worked on 0.8 and 0.10 firmware on Pro 1 devices.

**Comment by Chris-Schaefer-DE** [comment]
ok, first up: my apologies, found it, my bad: 
my PC time was in a "different time zone" => at least 2 seconds out (maybe 2 min and 2 sec) despite syncing to windows ntp server.
resyncd manually => works now.
(interval, string etc I checked)
retested today with Paypal, works. (now they only accept ONE OTP key)

**Comment by alex-nitrokey** [comment]
No worries.

>  (now they only accept ONE OTP key)

Yes, unfortunately.

**Comment by szszszsz** [comment]
@Chris-Schaefer-DE OK! Thank you for reporting, and retesting!

In case anyone would have similar issue and found this page, I will elaborate on the topic. 

Device is using host PC's time to calculate the TOTP code. To be precise, provided the service's webserver is time-synchronized, 2 seconds difference locally is 2 seconds less time to input the TOTP code. If the difference is greater than the selected `window_period` size (which is given in seconds; say the mentioned `30` ), it is impossible to match the code. 
Specifically, the window index used for the code calculation, which has to be the same on both sides, is:
```
window_index = floor(seconds_from_1970 / window_period)
```
which clearly changes on each multiple of the `window_period`.


@alex-nitrokey Could we establish FAQ regarding OTP cases?

**Comment by alex-nitrokey** [comment]
> @alex-nitrokey Could we establish FAQ regarding OTP cases?

I must admit, this wasn't fast, but I did it :)
Please have a look [here](https://www.nitrokey.com/documentation/frequently-asked-questions-faq#why-is-totp-is-not-working-for-me).
