### ISSUE TITLE
document CLI interface

### ISSUE THREAD

**Issue by jeroentbt** [Nitrokey/nitrokey-app#24]
The `nitrokey-app` provides the `--cmd` flag to "start a command line session".

There is however no easy to find documentation on its usage.

**Comment by jans23** [comment]
Valid point. However, we plan to drop ```--cmd``` flag altogether in favour of proper command line commands.

**Comment by jeroentbt** [comment]
No docs to tide us over?
ETA on proper CLI?

**Comment by jans23** [comment]
"--cmd" allows only the parameters "unlockencrypted" and "prodinfo". See src/ui/mainwindow.cpp:627ff
No ETA yet.

**Comment by jeroentbt** [comment]
That is indeed rather limited :)
Can't wait to be able to enter a OTP from my nitrokey through something dmenuish.

**Comment by varac** [comment]
a proper cli is also what prevents me to buy a nitrokey. only missing feature !

**Comment by szszszsz** [comment]
CLI is planned to be provided by separate project:
https://github.com/Nitrokey/libnitrokey
Please follow its development to be up to date.
