### ISSUE TITLE
macOS build artifacts are damaged

### ISSUE THREAD

**Issue by compeak** [Nitrokey/nitrokey-app#246]
This behaviour is observable with [1.0](https://github.com/Nitrokey/nitrokey-app/releases/download/v1.0/nitrokey-app-v1.0.dmg) and [1.1](https://github.com/Nitrokey/nitrokey-app/releases/download/v1.1/nitrokey-app-v1.1.dmg):

After installing the app shows this error:
![error1](https://cloud.githubusercontent.com/assets/1942208/26092653/6c3218d2-3a12-11e7-96d5-92451fc8445b.png)

Apparently the signature is broken:
![error_sig1](https://cloud.githubusercontent.com/assets/1942208/26092663/7fbe47d6-3a12-11e7-80c5-d68fe0836fe0.png)
(Signature checked with WhatsYourSign)

**Comment by szszszsz** [comment]
Added unsigned DMG binaries to v1.1 release.

**Comment by jans23** [comment]
@szszszsz What is needed in order to fix this issue properly? (not providing unsigned DMG)

**Comment by szszszsz** [comment]
@jans23 This message actually means that the code-signing certificate is not recognized in the OS or accepted for some reason and thus considered '`damaged`'.

**Comment by jans23** [comment]
I understand. But what do we need to do in order to provide properly
signed DMGs which are accepted by macOS?

**Comment by jonathancross** [comment]
Shooting in the dark here, but...

    spctl -a -t exec -vv /Applications/Nitrokey\ App\ v1.1
    /Applications/Nitrokey App v1.1: CSSMERR_TP_NOT_TRUSTED

Maybe these are of some use?
* https://stackoverflow.com/questions/31709087/failure-digitally-signing-a-mac-app-outside-xcode?rq=1
* https://stackoverflow.com/questions/13330183/cssmerr-tp-not-trusted-wwdr-certificate-this-certificate-was-signed-by-an-unk

**Comment by szszszsz** [comment]
Thank you for the suggestions. I have not tried yet the solution [(link)](https://stackoverflow.com/questions/22458027/mac-dmg-oddity-signing-and-damaged-applications/44847247#44847247) with separately signing out of the DMG, might be worth a try.

**Comment by szszszsz** [comment]
I have added recompiled bundles for versions `v1.0`+. Please retest v1.1 with `nitrokey-app-v1.1-qt5.9-signed.dmg` from [release](https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.1) page.
I will remove the unsigned packages after your confirmation it is working correctly.

**Comment by compeak** [comment]
Works for me:
![screen shot 2017-09-04 at 08 33 00](https://user-images.githubusercontent.com/1942208/30014282-bea355d2-914b-11e7-9740-d42217fff739.png)

**Comment by szszszsz** [comment]
OK! Thank you for checking. 
@GonZo @jonathancross  Please reopen in case it would not work on yours macOS installation.

**Comment by jonathancross** [comment]
Looks good to me :-)
```
spctl -a -t exec -vv  /Applications/Nitrokey\ App\ v1.1 
/Applications/Nitrokey App v1.1: accepted
source=Developer ID
```
