### ISSUE TITLE
macOS 10.12.5 - wrong information in the About Box - encrypted volume

### ISSUE THREAD

**Issue by Peacekeeper2000** [Nitrokey/nitrokey-app#248]
While I copied files on the encrypted volume ( and also after the copy) I see a menu entry giving me the possibility to lock the encrypted volume. On the other side the About box is showing a "inactive" for the encrypted volume. It should say "active" instead.

**Comment by szszszsz** [comment]
Hi!
I assume your device is Storage v0.45, is that right?
Please retest with latest version: [v1.2-beta.2](https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.2-beta.2).

**Comment by Peacekeeper2000** [comment]
Ok, it passed my tests. Yeah !
