### ISSUE TITLE
OTP generation always asks for User PIN

### ISSUE THREAD

**Issue by karthanistyr** [Nitrokey/nitrokey-app#250]
I have set up the nitrokey-app to protect OTPs by user PIN, and checked the "forget PIN in 10 minutes" box.
The app always asks for the user PIN, even if the subsequent OTP generations come within the 10 minutes window (for example, a few seconds after).

![image](https://cloud.githubusercontent.com/assets/7722196/26199510/2c130e6c-3bc2-11e7-966a-e54f7278dd65.png)

**Comment by karthanistyr** [comment]
I made a hopefully minimal change to restore the functionality in pull request https://github.com/Nitrokey/nitrokey-app/pull/256. I'm expecting this to only affect the PIN remanence (i.e. make the app remember the PIN for 10 minutes as expected).

**Comment by szszszsz** [comment]
Not closing yet, since PIN cache for Pro v0.7 is not implemented. However Pro v0.8 and Storage v0.48 (and earlier) are working.

**Comment by szszszsz** [comment]
Moved remaining work to separate issue. Pro v0.8 and Storage work as desired.
