### ISSUE TITLE
Can't add AWS MFA secret

### ISSUE THREAD

**Issue by bgaluszka** [Nitrokey/nitrokey-app#26]
I can't add AWS MFA secret to OTP and Password Safe. It cuts last 5 characters out of 64.

**Comment by jans23** [comment]
This is a known issue due to flash storage limitations. We might release a patch in the future when reorganizing the storage structure.

**Comment by bgaluszka** [comment]
Maybe it would be worth updating that post https://www.nitrokey.com/news/2012/oath-one-time-passwords-allow-login-gmail-dropbox-aws?

**Comment by jans23** [comment]
Good point. I updated the post from 2012. I may be able to announce more news on AWS support in the next two month.

**Comment by warci** [comment]
Any news on this? AWS mfa support is essential for me

**Comment by jans23** [comment]
We aim to solve this in the next release. But we don't have a release date yet.

**Comment by jans23** [comment]
This issue is now tracked here: https://github.com/Nitrokey/nitrokey-pro-firmware/issues/22

**Comment by szszszsz** [comment]
Please notice issue has been updated on Nitrokey Pro firmware project.
