### ISSUE TITLE
Clipboard is not cleared from user password

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#263]
- Application version: v1.1
- Operating system:  openSuse Leap 42.2, Manjaro
- Device model and firmware version: Pro (no version info)
- Connected USB port type: not related
- Issue occurrency: always

### Expected behaviour
Clipboard should be cleared of user password (supposedly PWS password).
Password contains unicode characters. Same behaviour is for ASCII-only password.

### Current behaviour
Password is not cleared.

### Details
More information on [support forum](https://support.nitrokey.com/t/nitrokey-passwords-the-clipboard-and-security/493/12?u=szszszsz).

**Comment by szszszsz** [comment]
Not reproducing on Nitrokey App v1.1 with:
- Ubuntu 16.10
- Windows 8.1
Might be platform specific. To retest on openSuse.

**Comment by jans23** [comment]
@techge could you test this issue with OpenSuse, please?

**Comment by techge** [comment]
Could not reproduce with:
OpenSuse Leap 42.3 (most recent version), Nitrokeyapp 1.1

It is either in prior Version (42.2) or not easily reproducible.

**Comment by jans23** [comment]
Did you try it using Unicode characters? (From the forum discussion, it sounds as this might be relevant)

**Comment by szszszsz** [comment]
Issue caused by clipboard manager. Closing as invalid.
Workaround proposed in #293
