### ISSUE TITLE
Configuration of Passwordsafe - wrong language shown

### ISSUE THREAD

**Issue by Peacekeeper2000** [Nitrokey/nitrokey-app#265]
- Application version: [e.g. v1.1 - it is shown in `About` window] -nitro-app 1.1
- Operating system: [name, version, 32/64 bits, kernel version (if Linux) ] - macOS 10.12.6
- Device model and firmware version: [Pro v0.8/Storage v0.45 etc.] NK Storage v0.45
- Connected USB port type: [1.1/2.0/3.0] - 1 of 2 :-) 
- Issue occurrency: [always/sometimes/once] always

### Expected behaviour
The GUI is using the system language for the dialog boxes.  So in German a "Slot x" is called "Eintrag x". Wenn you delete an entry with the button, an empty "Eintrag x" would be expected.

It is a small error / quality issue - but it prevents from trusting the GUI

### Current behaviour
Wenn you delete a Password entry , it will no longer called "Eintrag x" it will show as "Slot x". Wenn you close and re-open the dialog box, it will be shown correct as "Eintrag x".

### Steps for reproduction
Just delete a Password Slot entry and have a look on the first field.

#### Preconditions
[Device reinserted, Application just started, Application used for almost 30 minutes etc.]
Other Language than English is the System language

#### Steps
1. 
2. 
3. 
4. 

### Logs
[Please take logs and attach them as text files here when needed. For UI issues or `always` frequency it is not required but might increase investigation speed. [How to take logs?](https://github.com/Nitrokey/nitrokey-app/wiki/How-to-take-logs-in-Nitrokey-App-v1.1). To attach logs please `drag and drop` log file to the edit field.]

Logs attached: 
- no

**Comment by szszszsz** [comment]
Please retest with latest version: [v1.2-beta.2](https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.2-beta.2).

**Comment by szszszsz** [comment]
Not encountered with v1.2-beta.2, Ubuntu 16.10. Please reopen if it would occur on your side.
