### ISSUE TITLE
Password length higher then 20 letters 

### ISSUE THREAD

**Issue by beerisgood** [Nitrokey/nitrokey-app#269]
It is possible to save passwords with more then 20 letters? For some sites i use 30 letters but cant save that on my Nitrokey Pro

**Comment by jans23** [comment]
No. Because of limited hardware resources the password length is limited.

**Comment by beerisgood** [comment]
Too bad

**Comment by szszszsz** [comment]
Hi @beerisgood !
This is not the best workaround, but you could store your password in the `login` field, which is `32` bytes long. To copy it later you will have to open the `Configuration` window instead of using tray menu, which might be inconvenient.

**Comment by szszszsz** [comment]
Please follow https://github.com/Nitrokey/nitrokey-pro-firmware/issues/35 and https://github.com/Nitrokey/nitrokey-storage-firmware/issues/38 on this matter

**Comment by szszszsz** [comment]
Adding invalid label since this is not Nitrokey App's issue.
