### ISSUE TITLE
TOTP doesnt work with Amazon

### ISSUE THREAD

**Issue by beerisgood** [Nitrokey/nitrokey-app#270]
I cant add the Amazon key in Nitrokey to add the device. It looks the key lengh is to long for Nitrokey

**Comment by jans23** [comment]
Which Nitrokey you have and which firmware?

**Comment by beerisgood** [comment]
I have a Nitrokey Pro with 0.7 firmware

**Comment by szszszsz** [comment]
AWS secrets are 320 bits and they are handled on Nitrokey Pro v0.8. 
Related issue: https://github.com/Nitrokey/nitrokey-pro-firmware/issues/22
Pro v0.7 and Storage v0.48 (and lower) handles 160 bits.

**Comment by szszszsz** [comment]
Closing as invalid since this is not a Nitrokey App issue.

**Comment by beerisgood** [comment]
Can i flash my Pro to 0.8 firmware?

**Comment by szszszsz** [comment]
You can find instructions about flashing Pro devices on https://github.com/Nitrokey/nitrokey-pro-hardware (chapter Flashing). Please wait with it for a moment though.

**Comment by beerisgood** [comment]
Damn that is very hard.
Doesnt exist another way?

**Comment by szszszsz** [comment]
How about easier guides (just found in the web; not read):
https://www.nitrokey.com/documentation/programming
https://raymii.org/s/tutorials/Nitrokey_gnuk_firmware_update_via_DFU.html (treats about Nitrokey Start, but it is similar).

**Comment by beerisgood** [comment]
So it doesnt exist a way without break the case and just connect the Key via USB and use a tool?
I dont want break the case nor use such special cables

**Comment by szszszsz** [comment]
Unfortunately it is not possible.
As an alternative you can send it to Nitrokey for reflashing. This looks as the easiest way to handle this.

From the official side, opening the case will most likely damage it and the warranty might be void after that. Device's hardware damage (done after opening the case e.g. by shorting wrong pins during the flashing procedure) is probably not covered by the warranty too. New casing could be ordered if needed. For details you need to contact the support directly.

**Comment by beerisgood** [comment]
I hoped for sending the Key back for reflashing. Sounds good!
How can i do that?

**Comment by szszszsz** [comment]
Please write directly by email. [Contact details are provided on main site](https://www.nitrokey.com/contact).

**Comment by beerisgood** [comment]
Thank you!
