### ISSUE TITLE
Windows 10 scaling problem with Nitrokey App and high resolution screens

### ISSUE THREAD

**Issue by techge** [Nitrokey/nitrokey-app#273]
=> Mostly copy&paste from https://support.nitrokey.com/t/windows-scaling-problem-with-nitrokey-app/689

"I wanted to change the User/Admin PIN with the Nitrokey App in Windows 10 on a high resolution monitor. But the windows ‘Set User PIN’ and ‘Set Admin PIN’ do not scale properly (see attached screenshot). I had to change to the lowest possible screen resolution and set scaling to 100 % in order to see what I type into fields for the current and new PIN.[...]
The same problem occurs with the Change Firmware Password."

- Application version: unknown yet, probably 1.1
- Operating system: Windows 10
- Issue occurrency: always

### Expected behaviour
"Nitrokey support needs to adapt the layout of these windows to avoid this "

**Comment by szszszsz** [comment]
Reproduced on Ubuntu 17.04 by setting scaling factor to `1.5`.

**Comment by szszszsz** [comment]
Remove line https://github.com/Nitrokey/nitrokey-app/commit/0ab89519c2632702c943d3ab6976b1e6b875cc8a#diff-7ec3c68a81efff79b6ca22ac1f1eabbaR48 as it seems to cause scaling issues.

**Comment by szszszsz** [comment]
- [ ] Update images to higher resolution in https://github.com/Nitrokey/nitrokey-app/tree/master/images

**Comment by szszszsz** [comment]
Connected with #302.
Moving image update task there. Closing as general issues with scaling has been solved for now.
