### ISSUE TITLE
build: udev rules and bash completion is installed in /usr/usr/...

### ISSUE THREAD

**Issue by ignatenkobrain** [Nitrokey/nitrokey-app#275]
- Application version: v1.1
- Operating system: Fedora release 28 (Rawhide), x86_64, Linux version 4.13.0-1.fc28.x86_64 (mockbuild@bkernel02.phx2.fedoraproject.org) (gcc version 7.2.1 20170829 (Red Hat 7.2.1-1) (GCC)) #1 SMP Mon Sep 4 13:41:35 UTC 2017
- Device model and firmware version: irrelevant
- Connected USB port type: irrelevant
- Issue occurrency: always

### Expected behaviour
-- Installing: /home/brain/rpmbuild/BUILDROOT/nitrokey-app-1.1-1.fc28.x86_64/usr/lib/udev/rules.d/41-nitrokey.rules
-- Installing: /home/brain/rpmbuild/BUILDROOT/nitrokey-app-1.1-1.fc28.x86_64/usr/share/bash-completion/completions/nitrokey-app

### Current behaviour
-- Installing: /home/brain/rpmbuild/BUILDROOT/nitrokey-app-1.1-1.fc28.x86_64/usr/usr/lib/udev/rules.d/41-nitrokey.rules
-- Installing: /home/brain/rpmbuild/BUILDROOT/nitrokey-app-1.1-1.fc28.x86_64/usr/usr/share/bash-completion/completions/nitrokey-app

### Steps for reproduction
Just build nitrokey-app.

#### Preconditions
Have udev.pc and bash-completion.pc installed

**Comment by szszszsz** [comment]
Hi!
Could you paste what results are of the following commands?
```
PKG_CONFIG_EXECUTABLE=pkg-config
${PKG_CONFIG_EXECUTABLE} --variable=completionsdir bash-completion
${PKG_CONFIG_EXECUTABLE} --variable=udevdir udev
```

**Comment by ignatenkobrain** [comment]
```
[brain@ignatenko-w541 SPECS]$ PKG_CONFIG_EXECUTABLE=pkg-config
[brain@ignatenko-w541 SPECS]$ ${PKG_CONFIG_EXECUTABLE} --variable=completionsdir bash-completion
/usr/share/bash-completion/completions
[brain@ignatenko-w541 SPECS]$ ${PKG_CONFIG_EXECUTABLE} --variable=udevdir udev
/usr/lib/udev
```
