### ISSUE TITLE
build: translations are not installed

### ISSUE THREAD

**Issue by ignatenkobrain** [Nitrokey/nitrokey-app#276]
previously (v0.6.3) used to install `/usr/share/locale/de_DE/LC_MESSAGES/nitrokey-app.mo`, but now with v1.1 nothing like that is getting installed although qm files are generated..

**Comment by szszszsz** [comment]
Hi! I do not think this is necessary. Translations are now included directly in the binary (as a compressed resource). Let me know if there is a need otherwise.

**Comment by ignatenkobrain** [comment]
@szszszsz ah, I just don't know how Qt5 works with that =) This is fine.
