### ISSUE TITLE
nitrokey-app doesn't compile with latest libnitrokey

### ISSUE THREAD

**Issue by ignatenkobrain** [Nitrokey/nitrokey-app#279]
https://github.com/Nitrokey/nitrokey-app/blob/master/CMakeLists.txt#L233

```cmake
TARGET_LINK_LIBRARIES(nitrokey-app.debug
  ${EXTRA_LIBS}
  ${NK_LIB}-log
#  ${platform_specific_libs}
  Qt5::Widgets Qt5::Core Qt5::Gui
)
```

since https://github.com/Nitrokey/libnitrokey/commit/bb7e087979d9150b8ab8d28ffccc43a3eaddab35, nitrokey-log.so does not exist, so nitrokey-app.debug fails to compile.

**Comment by ignatenkobrain** [comment]
https://github.com/Nitrokey/libnitrokey/commit/2ea2883145b2ad06d437d3fcf06026583109791a is related too

**Comment by ignatenkobrain** [comment]
P.S. I don't want to use bundled version of libnitrokey so just trying to hotfix it by adding some compiler definition (NO_LOG) doesn't work for me.

**Comment by szszszsz** [comment]
Hi!
You are correct. The changes should be synchronized  with current `master`  in next two days. There is already a patch waiting to merge on https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.2-beta.2. You can try to test it instead in the meantime.

**Comment by ignatenkobrain** [comment]
@szszszsz hmm, can you link a patch/pull-request please? it seems that v1.2-beta.2 doesn't contain required changes..

**Comment by szszszsz** [comment]
Indeed, sorry, I will correct this asap.
So, to rephrase, you would like to use shared `libnitrokey` library (from other package)?
To make it so I think this line will have to be removed in hotfix: https://github.com/Nitrokey/nitrokey-app/blob/v1.2-beta.2/CMakeLists.txt#L35 and CMake should issue linking with on-system library (not tested yet).

**Comment by ignatenkobrain** [comment]
@szszszsz yes, I package libnitrokey separately which used to have 2 libraries at the same time =) I already have all hacks in place to use system-wide libnitrokey =)

**Comment by szszszsz** [comment]
Great! 
I have pushed the changes to [v1.2-beta](https://github.com/Nitrokey/nitrokey-app/tree/v1.2-beta) branch. Could you test it?

**Comment by ignatenkobrain** [comment]
Apparently I did same thing some time ago.. ;) https://src.fedoraproject.org/rpms/nitrokey-app/c/df8881ad4831ae1c8ef4a4c5fa223f7de42f7545

So I'm sure it works. Would be cool if you could tag some new beta version so I could update fedora to it.

**Comment by szszszsz** [comment]
Done! See [v1.2-beta.3](https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.2-beta.3) tag.

**Comment by ignatenkobrain** [comment]
Thanks a lot! Just built and submitted updates for F27+
