### ISSUE TITLE
OTP with Tutanota Mail (codec expects padded input string)

### ISSUE THREAD

**Issue by techge** [Nitrokey/nitrokey-app#280]
OTP can not be configured using the secret key offered by [Tutanota](https://tutanota.com/) Mail App (web application).

- Application version: 1.1
- Operating system: Does not matter (but ArchLinux 64 Bit here)
- Device model and firmware version: Pro and Storage
- Issue occurrency: always

### Expected behaviour
Save secret key from Tutanota web client and generate OTP afterwards

### Current behaviour
Crashes and says "Critical error encountered. Please restart application.
Message: parse error: codec expects padded input string but padding was invalid" when trying to save secret key in App

Example key: 'foci mzle sxw2 oxnw bnvk digw ju'

See [this forum](https://support.nitrokey.com/t/tutanota-2fa-totp-bug-with-nitrokey-crashes/693/5) thread.

I can contact developer if needed.

**Comment by techge** [comment]
Note: This probably is happening for other services (e.g. Amazon) as well as one user reported.

**Comment by szszszsz** [comment]
Hi!
Application accepts OTP secret given either in `hex` or `base32`. The example key is neither of these two. What format is it?
You can test the strings online e.g. [here](https://emn178.github.io/online-tools/base32_encode.html).
As for Amazon, more details are needed. It should work with Pro v0.8, see: https://github.com/Nitrokey/nitrokey-app/issues/270 https://github.com/Nitrokey/nitrokey-app/issues/26 .

**Comment by bedhub** [comment]
Hi there!
I am Bernd from Tutanota. The provided key is Base32 encoded only the padding (==) is missing . The link to the online tool you have provided encodes only to UTF-8 string and that does not work as our secret is not a UTF-8 string. It is just a random byte array. You can try this decoding tool http://tomeko.net/online_tools/base32.php?lang=en.

It would be great to solve this issue. You can register for free at https://mail.tutanota.com/signup and then you can configure TOTP in Settings->Login

**Comment by szszszsz** [comment]
Hi @bedhub!
Indeed, I was suspecting the lack of padding might be the case and I wanted to make sure this is the correct encoding. It is just a matter of string cleaning/formatting then, should not take long to fix it. Thank you for the reply!

**Comment by szszszsz** [comment]
Connected: #240

**Comment by szszszsz** [comment]
@techge Could you get TOTP secret example for Amazon too?

**Comment by techge** [comment]
I do not have access to an Amazon account. I could create one on thursday or may @jans23 can help us :)

**Comment by szszszsz** [comment]
OK, I have found it already - thank you! You might make the account anyway for independent testing though.
