### ISSUE TITLE
Create AppImage package

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#286]
Create AppImage package for App distribution on long release cycle OSes.
Similar to #114

**Comment by probonopd** [comment]
Check out the examples for how to use [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) on Travis CI, specifically:

* https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci
* https://github.com/probonopd/linuxdeployqt#projects-using-linuxdeployqt

**Comment by FrostKnight** [comment]
I look forward to 1.3! I wonder when that is coming out... :)

**Comment by dragon788** [comment]
I would love to see this so I can simply put the AppImage on the unencrypted partition of my Nitrokey storage and be able to open it on most distributions as it is simply a binary at that point. No needing to change the state of the system (adding PPA/snapd/etc) just to access my files.

I may take a whack at it if I get a chance between other projects.

**Comment by probonopd** [comment]
> I would love to see this so I can simply put the AppImage on the unencrypted partition of my Nitrokey storage and be able to open it on most distributions as it is simply a binary at that point. No needing to change the state of the system (adding PPA/snapd/etc) just to access my files.

Great use case! :+1:

**Comment by szszszsz** [comment]
Hi! I have uploaded AppImage for [v1.3-beta.1](https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.3-beta.1) to the release's download page. It was built on Ubuntu 16.04.4 LTS inside Docker container. It should be possible to build exactly the same binary using a builder located in [nitrokey-app.build project](https://github.com/Nitrokey/nitrokey-app.build/tree/master/docker/ubuntu_xenial) (work in progress).

**Comment by probonopd** [comment]
Thank you @szszszsz. Can you please build on Ubuntu 14.04.x? That is currently the oldest still-supported LTS release, and it's required that AppImages run on Ubuntu 14.04.x in order to be included in [AppImageHub](https://appimage.github.io/apps/). See https://github.com/probonopd/linuxdeployqt/ for examples on how to do this while still using new versions of Qt.

**Comment by szszszsz** [comment]
Actually, the issue is with requiring GCC 5.0+ compiler (C++14 to be specific), which 14.04 is not providing as far as I remember. I can install newer, as one does with Travis CI, but have not tested this yet. Do you know any success stories?

**Comment by probonopd** [comment]
If you install a newer (C++14) compiler on 14.04, then it pulls in a newer libstdc++, which creates trouble if not handled properly. Luckily we have a solution for that: https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

**Comment by szszszsz** [comment]
Updated release page with new build, done on Ubuntu 14.04: [link](https://github.com/Nitrokey/nitrokey-app/releases/download/v1.3-beta.1/Nitrokey_App-x86_64-v1.3-beta.1-1-gfbd3c57-14.04.AppImage).
Made using modified previous builder: [nitrokey-app.build/support_14.04](https://github.com/Nitrokey/nitrokey-app.build/tree/support_14.04/docker/ubuntu_xenial).
Feedback welcomed!

**Comment by probonopd** [comment]
Thanks. Triggered a re-run of the test.

**Comment by probonopd** [comment]
Looks like it is working. I think the 16.04 one can be deleted, since it is no longer needed.

**Comment by probonopd** [comment]
Possibly graphics are missing, please make sure you are loading them from a location _relative_ to the _main executable_, e.g., using `QString QCoreApplication::applicationFilePath() `.

![icons](https://user-images.githubusercontent.com/2480569/38146394-15e64c96-344e-11e8-8299-219ec1aa0926.png)

**Comment by FrostKnight** [comment]
On 03/30/18 13:11, probonopd wrote:
> Possibly graphics are missing, please make sure you are loading them from a location _relative_ to the _main executable_, e.g., using `QString QCoreApplication::applicationFilePath() `.
>
> ![icons](https://user-images.githubusercontent.com/2480569/38146394-15e64c96-344e-11e8-8299-219ec1aa0926.png)
>
>
This works on my distro also. I use a distro that is based on archlinux
using debian packages. ;)

so far so good I say!

**Comment by szszszsz** [comment]
Thank you for the test and feedback!

@FrostKnight Great! Quite interesting distro - how is it named?
@probonopd This is probably some kind of QtSvg library dependency, which is missing on 14.04 (we switched to SVG format lately). The graphics binaries themselves are integrated into binary (via Qt resources). Could you share how the test was conducted? Are you running the binary on a VM with 14.04?

**Comment by FrostKnight** [comment]
On 04/04/18 03:26, Szczepan Zalega wrote:
> Thank you for the test and feedback!
>
> @FrostKnight Great! Quite interesting distro - how is it named?
Hyperbola is the distro. It is on this website, Hyperbola.info

It will be using libressl and the first fully free software distro to do
so... Although it hasn't been approved by the fsf yet, it will be
eventually.

Yeah, it also uses a hardened linux libre kernel and other good stuff...

Long story short, It is an awesome distro.

Look on the website for more info though. :)

**Comment by probonopd** [comment]
> Are you running the binary on a VM with 14.04?

Yes. The test is running on a 14.04 machine on Travis CI, using [this](https://github.com/AppImage/appimage.github.io/blob/master/code/worker.sh) script.

**Comment by szszszsz** [comment]
Closing as the initial task is mostly finished. Moving support for Svg images on 14.04 to a separate issue - will be provided later, after the release. Issue: https://github.com/Nitrokey/nitrokey-app/issues/340.
