### ISSUE TITLE
Smart dialogue for firmware password

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#289]
Perhaps we could make the dialogue for firmware update easier by assuming the firmware password is default. So the Nitrokey App could try using the default firmware password in the background before presenting a dialogue to the user. It would only prompt for the firmware password if it is not default.

Note: We can't apply the same approach to User or Admin PIN because those have a PIN counter.

**Comment by alex-nitrokey** [comment]
I am a bit confused. The App states, that the firmware password can only put in wrongly three times. This isn't true?
![screenshot_20180308_110443](https://user-images.githubusercontent.com/36155797/37145185-87da434c-22c0-11e8-911b-75faa6d19fac.png)
So either this feature is harmful (as potentially increasing the counter) or the message should be different for firmware password.

**Comment by szszszsz** [comment]
I do not see anything about 3 attempts here :-) Only the length is mentioned.
Apart from that here are PINs mentioned while should be passwords (to be exact), everything is correct.
There is no attempts limit on firmware password, which means classical brute-force is possible, though each attempt take about 1 second making it not feasible.

**Comment by jans23** [comment]
Looking at the screenshot, the middle paragraph (about PINs) should be removed and the last paragraph (warning) should be highlighted in bold.

**Comment by szszszsz** [comment]
- [ ] `the middle paragraph (about PINs) should be removed `
- [ ] `the last paragraph (warning) should be highlighted in bold.`

While we are changing this form, I would add a paragraph about the length limits of firmware passwords as well; that it is not a part of smart card PINs and it has no attempts counter (the last two as a reminder).
What do you think?

**Comment by jans23** [comment]
Ok
-- 
Sent from a mobile device.

**Comment by szszszsz** [comment]
Changing to:

![screenshot from 2018-03-10 13-52-00](https://user-images.githubusercontent.com/17005426/37242464-48fc5934-246a-11e8-89d1-c10ddbc4be6b.png)

**Comment by jans23** [comment]
I think the minimum is 8 and not 6 characters, isn't it?

I suggest the following text:

> Current firmware password (default: "12345678"):
> 
> New firmware password:
> 
> New firmware password:
> 
> Other than PINs, the firmware password doesn't has a retry counter and therefore doesn't prevent password guessing attacks. A secure firmware password should contain lower and upper case letters, numbers and special characters with a length between 8 and 20 characters. 
> 
> Once the firmware password is forgotten, the Nitrokey can't be updated or reset. Please don't loose your firmware password.

**Comment by jans23** [comment]
Just in case the sentence "A secure PIN..." has been borrowed from another dialogue. A 6 digit PIN consisting of numbers is sufficiently secure and it doesn't need characters or special characters. Therefore the sentence should be removed from the application entirely.

**Comment by szszszsz** [comment]
I have tested it - Storage allows 6 chars for firmware password's limit. I can increase it in the App; could be done so on firmware side as well.

- [ ] remove the 'A secure PIN...' text
- [ ] change the text
- [ ] increase required firmware password size

**Comment by szszszsz** [comment]
@jans23:
1. Regarding 'A secure PIN...', this is a (English) translation of string:
> You can use upper and lower case, numbers, and special characters.

In that case, could the original string stay, since it actually informs user about characters range?
2. I would leave default firmware password value in separate paragraph, since it will force the password edit fields to decrease their size (and whole password will not fit and be visible). This could be solved by increasing the window size in turn, but will create a lot of empty space as well.

**Comment by szszszsz** [comment]
Current windows for firmware password:
![screenshot from 2018-03-13 13-41-31](https://user-images.githubusercontent.com/17005426/37342247-48fa63f2-26c4-11e8-9101-bb60afaebe37.png)
And for PIN:
![screenshot from 2018-03-13 13-42-19](https://user-images.githubusercontent.com/17005426/37342289-66cef32a-26c4-11e8-908e-e8d2791fac88.png)

**Comment by szszszsz** [comment]
Changes merged in: https://github.com/Nitrokey/nitrokey-app/commit/ddbfc68e5e87c0affea6ea6937d24b1087b37cf7

**Comment by szszszsz** [comment]
- [ ] Change Firmware Password. Suggestion is to change the fields to the following:
> Current Firmware Password
New Password
Confirm New Password
xx-------------------xxx
The Firmware password doesn’t have a retry counter, and therefore doesn’t prevent against password guessing attacks. A secure and complex password should be created with the use of; lower and upper case letters, numbers and special characters with a length between 8 and 20 characters.
Default firmware password is; ‘12345678’.
xx-------------------xxx
WARNING! If you lose your Firmware password, Nitrokey can’t be updated or reset!

- [ ] Set User PIN:
>Current User PIN
New PIN
Confirm New PIN
xx-------------------xxx
Nitrokey prevents against brute force password guessing attacks by allowing a maximum of 3 incorrect PIN attempts. Therefore a PIN of 6 or 8 digits is sufficient. The PIN must be between 6 and 20 characters (8 for admin).
xx-------------------xxx
NOTE This rule does not apply to the firmware password, which must be complex for security reasons.

**Comment by szszszsz** [comment]
Applied changes from the feedback:
![screenshot from 2018-03-14 16-50-59](https://user-images.githubusercontent.com/17005426/37413728-ec68b050-27a7-11e8-9fde-52445b0f1fca.png)
![screenshot from 2018-03-14 16-50-49](https://user-images.githubusercontent.com/17005426/37413730-ecc1feb2-27a7-11e8-866f-6bc2cd85b17f.png)

![screenshot from 2018-03-14 16-53-54](https://user-images.githubusercontent.com/17005426/37413900-4af54dae-27a8-11e8-8edc-74b43a671b92.png)

**Comment by szszszsz** [comment]
Wording could be later changed by editing English translation, located in: `/i18n/nitrokey_en.ts`
