### ISSUE TITLE
Application icon looks poor

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#297]
The application icon on Windows (to double-click on) looks poor. It looks like the icon is available in a low-resolution and been scaled. Tested on a full-HD screen. Potentially this issue exists on other OS too.

**Comment by szszszsz** [comment]
Already fixed on MacOS: https://github.com/Nitrokey/nitrokey-app/issues/20

**Comment by szszszsz** [comment]
On Ubuntu 17.04/Unity App icon looks correct in applications' list.

**Comment by szszszsz** [comment]
![windows-icon-preview-v1 2-beta 4](https://user-images.githubusercontent.com/17005426/33514523-d2ecceb0-d755-11e7-9bd2-d0f3d34adf0f.PNG)
Added comparison between old and new icons.
