### ISSUE TITLE
Let user know App can be closed during the initialization

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#299]
> When initializing a Storage there is a process window. When opening the help window you can not close it because the process is in front of it. This is not bad if user is not frightened to close the process window. As this has no effect on initializing I would suggest we add a note to the process window which states that it is safe to close this window and that the process will be shown on app try as well.

---

Edit: Changed to:
- [x] instead close About and Configuration windows on SD card initialization start, see https://github.com/Nitrokey/nitrokey-app/issues/299#issuecomment-351335980

**Comment by jans23** [comment]
Instead of adding a potentially confusing information, I suggest to make the about window (or any other window) closable while the progress window is displayed.

**Comment by szszszsz** [comment]
I will remove then the `modal` attribute from the progress window.

**Comment by jans23** [comment]
What does the modal attribute do? We shouldn't allow the user to trigger new actions while the progress bar is active.

**Comment by szszszsz** [comment]
`Modal` window stays on top of the others and blocks actions on other application windows and tray menu until closed. When shown it has focus. Linking Qt 5 documentation about [modal attribute.](https://doc.qt.io/qt-5/qwindow.html#modality-prop)
For this specific case I can instead close About and Configuration on SD card initialization start.

**Comment by jans23** [comment]
I think that would be the best.
-- 
Sent from a mobile device.
