### ISSUE TITLE
Conditionally compile libappindicator support.

### ISSUE THREAD

**Issue by cjsthompson** [Nitrokey/nitrokey-app#3]
Most Linux distributions do not use neither unity nor libappindicator. It would be nice if libappindicator support could be switched off at compile time so that it's many dependencies won't have to be loaded on systems which make no use of libappindicator.

**Comment by jans23** [comment]
We use libappindicator to abstract the tray-icon and notification among different desktop environments. Switching it off would mean to replace it by another method. Do you have any particular replacement in mind?

**Comment by cjsthompson** [comment]
I didn't know libappindicator could do this sort of abstraction. But Qt 5.5 can as well :

http://doc.qt.io/qt-5/qsystemtrayicon.html#details

**Comment by jans23** [comment]
Do you have time to fix this issue? That would be great.

I assign this to the backlog because it isn't of priority for us.

FYI: Previously when we tried Qt (I think 5.0 or 5.1 or something) it didn't work well. In Linux the notifications weren't really "native" and the tray icon appeared at a wrong position. libappindicator solved these problems for us.

**Comment by cjsthompson** [comment]
I'm aware of that. I actually have the problem with nitrokey-app's trayicon which when started appears or not in the taskbar randomly (I'm using Xfce). So I researched the problem. And at least for the tray icon problem, according to what I've read it, is now fixed in Qt 5.5 as they have now implemented the latest standards in trayicon handling. As far as the notifications go I don't know.

I do have time to fix this issue. Though I only know C and have OOP experience with Java and PHP. So if I give it a try, I can't promise to do something flawless by C++ programming standards.

**Comment by jans23** [comment]
Please feel free to give it a try and we would provide you feedback.

**Comment by cjsthompson** [comment]
Sorry it took a while, but I've just sent you a pull request to allow optionally compiling out libappindicator support on Linux. I thought It would be much harder, but in fact it was trivially easy to do. As expected, there is no more problem with the tray icon with Qt 5.5.
