### ISSUE TITLE
Exception after checking HOTP password with open configuration form

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#30]
occurency: always
os: ubuntu 15.04
stick: nitrokey pro
cause: unknown, involved Qt warning box
severity: medium

scenario:
1. Open nitro-app
2. Configure HOTP slot (enter correct data and save), do not close configuration form
3. Click on tray and get password from slot just set
4. Choose in configuration form slot just saved
5. Enter same data as in step 2
6. Click Save
7. Enter proper admin PIN

**Comment by szszszsz** [comment]
Apparently with Nitrokey Pro one cannot set HOTP configuration more than once in application life (-> after each HOTP entry the application has to be restarted).

**Comment by jans23** [comment]
@szszszsz Is this issue solved because of #149 ?

**Comment by szszszsz** [comment]
It is possible. I will retest with issue's scenario.

**Comment by szszszsz** [comment]
@jans23 Indeed this one is not occurring. It was a variation of #142 .
