### ISSUE TITLE
v.1.2-beta.4 not cooperating with VM/Virtualbox (Windows'es 7/10 do not detect the device)

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#300]
> on Win7, Win10 and Ubuntu 17.10 App 1.1 is working fine on Virtualbox, but not 1.2-beta.4 What I also realized is that using App 1.1 on Ubuntu 17.10, closing it, installing App 1.2, starting without ejecting the Nitrokey works fine until you disconnect once.

**Comment by techge** [comment]
It seems like it has something to do with scdaemon. At least on Ubuntu 17.10 it is working now after installing scdaemon. If this is true, it is probably a good idea to make scdaemon a dependency of nitrokey-app.
Although it is mentioned as needed for GnuPG on website, it is not marked as needed for App to work.

**Comment by szszszsz** [comment]
Issue with Windows is resolved now (pending being added to repository). About Ubuntu 17.10 I got confused - is this still occurring?
App is not using `scdaemon` - it communicates directly with `libhidapi` and `libusb`. Could you try to run the App with it removed (and its dependencies)?

**Comment by techge** [comment]
GnuPG needs scdaemon to work with OpenPGP Card. After removing scdaemon, App recognizes the Nitrokey only if it was recognized before when scdaemon was yet installed. When I disconnect the Nitrokey and try again, it will not get recognized anymore.

Tried with Pro and OPC2 and Storage with OPC3.

The App may not need scdaemon directly, but as it make use of GnuPG functions (or not?) it may depend on it?

This may is not a VM/Virtualbox issue at all 🤔 Will try on "real" Ubuntu 17.10 (really :wink:).

**Comment by szszszsz** [comment]
I see. Could you briefly list `scdaemon` dependencies on 17.10?
Perhaps some of them should be included in App's deps too.

**Comment by techge** [comment]
I will look at it later. But I can confirm: "real" Ubuntu 17.10 is the same behavior -> uninstalling scdaemon *only* removes ability to detect Nitrokey if not detected earlier.

**Comment by szszszsz** [comment]
Moving `scdaemon`-related issue to https://github.com/Nitrokey/nitrokey-app/issues/310

**Comment by szszszsz** [comment]
This will be closed on merging Windows-related fix.
