### ISSUE TITLE
Icons in vector-format and in system color

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#302]
Using icons in vector format should be possible according to [1] and [2].

Investigate how coloring on the fly and using text's color can be implemented. It would be done automatically, if the image would be a font glyph like in [3]. Lets wait for the icons first.

[1] http://doc.qt.io/qt-5/qicon.html
[2]
https://stackoverflow.com/questions/8551690/how-to-render-a-scaled-svg-to-a-qimage#8551810
[3] https://github.com/gamecreature/QtAwesome

**Comment by szszszsz** [comment]
Tested on Windows 8.1, macOS 10.12.6 and Ubuntu 18.04/Gnome 3.27.
Merged to master.
