### ISSUE TITLE
Ubuntu / not detecting devices without scdaemon with installed CMake/CPack created package

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#310]
Devices are not detected by the App, if the `scdaemon` package is not installed.
Environment: Ubuntu 17.10
Installed through .DEB package, made by CMake/CPack.

Previous description below:

----

Devices are not detected by the App, if the `scdaemon` package is not installed.

Environment: Ubuntu 17.10
Details: https://github.com/Nitrokey/nitrokey-app/issues/300
> Tried with Pro and OPC2 and Storage with OPC3.

**Comment by techge** [comment]
How does the App handle the factory-reset of OpenPGP Card? Doesn't it use scdaemon? I still do not see why the Nitrokey is not detected at all, but I was surprised, that you said App isn't using scdaemon at all...

**Comment by szszszsz** [comment]
Factory reset is executed by sending HID command to device, where it is handled further. uC sends similar to GnuPG/scdaemon reset commands to smartcard.

**Comment by techge** [comment]
It is already there since 1.2 beta 2. Maybe it helps... I had no beta 1 version, so it is anywhere between 1.1 and 1.2 beta 2...

**Comment by szszszsz** [comment]
How do you install it?

**Comment by techge** [comment]
Using the github pre-releases.

**Comment by szszszsz** [comment]
Do you mean the RPM file from Github releases?
And I guess the command is `dpkg -i`?

**Comment by techge** [comment]
No, there are .deb files which work far more better :)
Yes, I used dpkg --install

**Comment by szszszsz** [comment]
Ok, I will check it too later. It is almost surely dependency-related.
Packages were built on 16.04 AFAIR.

**Comment by techge** [comment]
Alright. Maybe it will not occur if built via launchpad repos anyway?

**Comment by szszszsz** [comment]
Perhaps. But it would be great if standalone package would install its deps too when possible.

**Comment by jans23** [comment]
The scdaemon package was introduced in Ubuntu 17.10. I guess this issue is related to UDEV rules which are part of scdaemon.

**Comment by szszszsz** [comment]
Confirmed on Ubuntu 17.04 - `60-scdaemon.rules` file contains the rules for accessing Nitrokey devices.
To investigate, why the DEB package has not installed its UDEV rules.
@techge Could you see if there is a `41-nitrokey.rules` file  in paths
/etc/udev/rules.d/   
/lib/udev/rules.d/   
after the .DEB package installation?

**Comment by techge** [comment]
No, not with .deb package, only when using launchpad version (which is consequently working fine even when scdaemon is removed).

**Comment by szszszsz** [comment]
OK - so the problem lies in CMake/CPack.
Confirmed Debian/Launchpad packages contain udev rules.

**Comment by szszszsz** [comment]
AFAIK fixed with modern releases. Closing.
