### ISSUE TITLE
Add metainfo file for Linux software stores

### ISSUE THREAD

**Issue by rugk** [Nitrokey/nitrokey-app#312]
The app is not shown in GNOME Software.  So you may add some meta data to see it there.

See https://bugzilla.redhat.com/show_bug.cgi?id=1534140 for Fedora bug report.

**Comment by szszszsz** [comment]
Hi!
Is this the same as https://github.com/Nitrokey/nitrokey-app/issues/274 ?

**Comment by rugk** [comment]
Hu, no?

I just want to see the app in GNOME Software, that's the "application store" in GNOME and Ubuntu e.g.
I also found out the correct term is: metainfo` file. So you need to add a small metainfo file with some description, images and so on, and then one appears un GNOME Software (and as it seems, other stores). That whole thing seems to be called AppStream:

* https://en.wikipedia.org/wiki/AppStream
* https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by szszszsz** [comment]
I see. Which GNOME version do you use? I remember it was working with 3.26 - the App was listed and could be executed.

**Comment by rugk** [comment]
![grafik](https://user-images.githubusercontent.com/11966684/35097644-4f32e566-fc51-11e7-9f86-eedaf6ad0567.png)

Gnome 3.26, it is only available from Snap, but I'd prefer the official distro repo here (where it is available, see Fedora issue above). Fedora 27

**Comment by szszszsz** [comment]
I understand now. OK! I will create the metafile. It should be available from the next release.

**Comment by szszszsz** [comment]
Merged to master: https://github.com/Nitrokey/nitrokey-app/commit/71e134ff7599f0c8b3df72c094b0d51986cf44ef
It should show up on package update. If not, please ask the package's maintainer. Appstream file is placed in `/data` and it is copied on CMake install to `/usr/local/share/metainfo` (or similar) directory.
