### ISSUE TITLE
Warn user about old Storage firmware on MacOS

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#314]
Remove redundant code warning user about not correctly working Storage v0.48 on MacOS, if such combination would occur on his/hers system. Instead ask for upgrade on MacOS for any of firmwares older, than v0.50.
See #287 for details.

- [ ] Do not show further warnings on user's request

**Comment by jans23** [comment]
Instead of this warning, I suggest a warning for every device with a
firmware small than 0.50 to install firmware updates. This would be
useful for macOS only.

>

**Comment by szszszsz** [comment]
Corrected the title and description. Perhaps users should see this message on other OSes too? Latest fixes should be usable for all of them (it is true, that MacOS users benefits most of them).
