### ISSUE TITLE
Building a static binary for Linux

### ISSUE THREAD

**Issue by alexwh** [Nitrokey/nitrokey-app#323]
Hi there,

I've been trying to wrap my head around the cmake build system in order to generate static binaries for nitrokey-app. I thought it would be useful to store on unencrypted space along with the Windows and OS X apps, for situations where you'd need to access it on a box without internet access, and possibly certain dependant libraries.
I have attempted to build the project with cmake -DBUILD_SHARED_LIBS=OFF however this results in a dynamically compiled binary according to `file`. I believe this is due to the cmake file [using the packaged submodule of libnitrokey](https://github.com/Nitrokey/nitrokey-app/blob/master/CMakeLists.txt#L214). The Fedora package of libnitrokey{,-devel} does not seem to include a pkg-config definition, so cmake can't find it.
What would be the correct method of building the application statically, while using the git submodule?

Thanks!

**Comment by szszszsz** [comment]
Hi!

I will check it. Bundled, static build should work out of the box, without switches. Which Fedora version do you use?
And to clarify, you have `libnitrokey` package installed in the system already, am I right?

**Comment by alexwh** [comment]
Hi there,

I attempted to build with both with the Fedora library installed and not installed from dnf. I'm running Fedora 27. The issue I seemed to be getting was due to pkg-config not being able to find the system library, if `libnitrokey` was installed or not, it would take the `else()` branch, and print "Using bundled libnitrokey". 

Thanks!

**Comment by szszszsz** [comment]
Attached full run log:
[run.log.gz](https://github.com/Nitrokey/nitrokey-app/files/1731207/run.log.gz)

**Comment by szszszsz** [comment]
Hi @alexwh ! In case it would not be solved for you please reopen or comment.

Closing as not an issue (question).
