### ISSUE TITLE
Nitrokey does not show up in app on macbook with usb-c ports

### ISSUE THREAD

**Issue by steffenmllr** [Nitrokey/nitrokey-app#328]
- Application version: `1.2` (latest)
- Operating system: `osx 10.13.3` (latest)
- Device model and firmware version: `Storage v0.50` (latest)
- Connected USB port type: `USB-C via USB3.0 adapter` (tried different adapters)
- Issue occurrency: `always`

### Expected behaviour
The nitro key should be detected on a usb-c connection (adapter)

### Current behaviour
The nitro key does not show up in the app, but gets mounted as normal usb drive

### Steps for reproduction
Get a new macbook with only usb-c ports and use any adapter. So far i've tried 3 different brands. The nitrokey works as expected on an older macbook with normal usb ports.

**Comment by szszszsz** [comment]
Hi @steffenmllr ! Thank you for the report. 
1. Could you tell me, what OS version did you use on the older macbook while testing?
2. Nitrokey App uses HID interface to connect to the device. It is used also by USB mouse and keyboard - could you connect one of them through the adapter to see, whether HID is not blocked?
3. If you have `Secure Input` enabled - could you disable it and re-test?

**Comment by steffenmllr** [comment]
2. got me thinking: I'm using [Karabiner-Elements](https://github.com/tekezo/Karabiner-Elements) to remap my `^` key to `Esc` (german keyboard). When I closed the application everything worked as expected. Looks like Karabiner-Elements is messing with the HID interface.

Thanks for your fast reply! Closing this since I got it working again.

**Comment by szszszsz** [comment]
You are welcome and thank you as well for solving! 
I will keep in mind to ask first about keyboard customization software in case of similar issues.

cc: @alex-nitrokey (You may find this interesting as well)
-- 
Closing as invalid since direct cause is outside App.
