### ISSUE TITLE
AppImage: support for Svg on Ubuntu 14.04

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#340]
Currently built AppImage binary is not showing Svg images, while run on Ubuntu 14.04. 
Details: https://github.com/Nitrokey/nitrokey-app/issues/286

**Comment by szszszsz** [comment]
To retest

**Comment by jans23** [comment]
We support the latest LTS version only which is Ubuntu 18.04 now.
-- 
Sent from a mobile device.

**Comment by szszszsz** [comment]
Could be closed then. 
It should work on Ubuntu 16.04 as well already. And the AppImage builds are done on U14.04 AFAIR, so some compatibility should be maintained.
