### ISSUE TITLE
Please provide possibility to auto-start nitrokey-app minimized or in systray

### ISSUE THREAD

**Issue by Polynomial-C** [Nitrokey/nitrokey-app#349]
[Please fill in below details as much as possible and remove this line and other unneded data. Please provide more details for issues occurring less often.]

- Application version: [e.g. v1.1 - it is shown in `About` window]
1.3
- Operating system: [name, version, 32/64 bits, kernel version (if Linux) ]
Gentoo GNU/Linux 64bit kernel-4.14.34
- Device model and firmware version: [Pro v0.8/Storage v0.45 etc.]
Nitrokey-Pro
- Connected USB port type: [1.1/2.0/3.0]
2.0/3.0
- Issue occurrency: [always/sometimes/once]
always

### Expected behaviour
When logging into KDE, nitrokey-app should start itself in systray (like in previous versions)

### Current behaviour
When logging into KDE, nitrokey-app window pops up

### Steps for reproduction
Log into KDE (KF5 in my case), start nitrokey-app, save KDE session, logout, re-login

#### Preconditions
none

#### Steps
1. Log into KDE (KF5 in my case)
2. start nitrokey-app
3. save KDE session (can be configured to happen on logout)
4. logout
5. re-login

### Logs

Logs attached: 
-

**Comment by oderwat** [comment]
Same on OS X (see https://github.com/Nitrokey/nitrokey-app/issues/343). I don't know why this was changed but I doubt that it got enough thinking.

**Comment by alex-nitrokey** [comment]
On the one hand it was necessary to have a main window for the App (see changes in Gnome #274 ) and on the other hand there were many users who had problem with "the App not starting", because they did not recognized it in system tray.
IMHO it is a good idea to let a full featured window start. It is still a legit proposal to have a option to start in system tray though. Let's see what @szszszsz says about it...

**Comment by szszszsz** [comment]
These were precisely the reasons. App earlier had no main window hence it had nothing to show on start. Sure, there is no problem with adding such option to settings, so the App will execute minimized, but on the very first run will always show up.

**Comment by oderwat** [comment]
On Mac there is still a difference between running in the "tray" and running in the "dock". So please make sure that, if you add an option for that, there is also a way to get rid of the dock icon. It is pretty annoying to have a background program sitting in the dock and the "tray" all the time.

**Comment by VanNostrand** [comment]
How is the autostart implemented anyways? Yesterday I had two instances of nitrokey-app running, today I have three instances runnig when my plasma session starts.

**Comment by VanNostrand** [comment]
yeah, rebooted my PC and now I have 4 instances of nitrokey-app running

**Comment by alex-nitrokey** [comment]
This reminds me of [this](https://support.nitrokey.com/t/nitrokey-app-loads-multitude-of-times-with-kde-and-opensuse-rpms/627)...

I think it's something about Plasma, but I couldn't work it out in the past :thinking:

**Comment by heikojansen** [comment]
+1 for adding an option to show no window when auto-starting on login. 
It's quite annoying that one always needs to manually close the window.
