### ISSUE TITLE
Firmware export: tell user where the export was saved

### ISSUE THREAD

**Issue by alex-nitrokey** [Nitrokey/nitrokey-app#363]
- Application version: all, here: 1.3
- Operating system: all, here: Arch Linux
- Device model and firmware version: Storage, 0.50
- Issue occurrency: always

### Expected behaviour
Tell user where the export was saved, when firmware export to file function is used.

### Current behaviour
Only success of export is mentioned

A [user requested the feature (point 1)](https://support.nitrokey.com/t/kompliziert-und-eine-menge-fails-auf-einmal-bin-kurz-vor-umtausch/1152) to being able to decide where the export is saved. As far as I can see this is done by the firmware and therefore it is not desirable to change something on this behaviour. Instead, the user should at least get informed to avoid confusion.

**Comment by alex-nitrokey** [comment]
Sorry for the duplication, I had a bit trouble managing git :blush: 

Is this how it works? How will the other languages notice the change? Or how is the workflow working? (sorry for the questions...)

**Comment by szszszsz** [comment]
Hi Alex!

No problem! Please make the PR with a information, which issue will be fixed with it. Details should be [here](https://guides.github.com/introduction/flow/) or similar sites explaining `Github workflow`.

Regarding the translation - how about adding the exported file name as well? I think this is `firmware.bin`, but I am not sure.

**Comment by alex-nitrokey** [comment]
> No problem! Please make the PR with a information, which issue will be fixed with it. Details should be here or similar sites explaining Github workflow.

Yeah, I already realized that making a PR with master branch is a bad idea, but somehow forget the other day. This messed up some things. 

Good idea, I will add it in the PR I'll create. I just wasn't sure if that's the way to change the original string...

**Comment by szszszsz** [comment]
Fixed through https://github.com/Nitrokey/nitrokey-app/pull/364, but missed automatic closing.
