### ISSUE TITLE
nitrokey-app: symbol lookup error

### ISSUE THREAD

**Issue by suntorytimed** [Nitrokey/nitrokey-app#365]
- Application version: 1.3-4.14 (installed from openSUSE:security repo)
- Operating system: openSUSE Tumbleweed snapshot 20180606 Kernel 4.16.12-2-default with plasma
- Device model and firmware version: Pro v0.8
- Connected USB port type: 3.0
- Issue occurrency: always

### Expected behaviour
Nitrokey App is started
### Current behaviour
Nitrokey App crashes at start
### Steps for reproduction
Start Nitrokey App in terminal or via menu entry
#### Preconditions
Nitrokey Pro doesn't have to be plugged in to reproduce

#### Steps
1. start nitrokey-app via terminal

### Logs
`nitrokey-app: symbol lookup error: nitrokey-app: undefined symbol: _ZN8nitrokey15NitrokeyManager31set_encrypted_volume_read_writeEPKc`

**Comment by szszszsz** [comment]
Hi! You need to have `libnitrokey` package updated as well. Having Nitrokey App newer than `libnitrokey` might result in such behavior. Other way around should work well.

**Comment by suntorytimed** [comment]
@szszszsz Hi, libnitrokey is installed in version 3.3

**Comment by szszszsz** [comment]
I see - this version should work. Another possibility is to have both built using a different versions of the compilers, which could generate a different symbol names/table.
Could you give a try our AppImage release?

**Comment by suntorytimed** [comment]
The AppImage does work. I opened up a bug on openSUSE Open Build Service to fix the package.

**Comment by szszszsz** [comment]
Could you link it here in case they would have any suggestions?

**Comment by suntorytimed** [comment]
https://bugzilla.opensuse.org/show_bug.cgi?id=1096910

**Comment by szszszsz** [comment]
Thank you!

**Comment by suntorytimed** [comment]
After a rebuild with the new Qt libraries it still doesn't work for me. I have tried installing it on a clean VM with Tumbleweed and it works there (same snapshot level of Tumbleweed, same Kernel and same version of the packages). It seems like some kind of configuration or another package collides with the app.

**Comment by szszszsz** [comment]
A blind guess - perhaps you are using both packages from mixed sources/repositories on your original system (e.g. libnitrokey from a security updates, nitrokey-app from main system repository) and these happen to use different major compilers' versions.
Sadly I do not know openSUSE enough to give other hints. Please let me know, if you would solve this.

**Comment by suntorytimed** [comment]
All Nitrokey packages are part of the same additional repository and build there. It shouldn't be affected by different compilers. But there were some Qt updates in the last week which could have an influence.

**Comment by szszszsz** [comment]
I see. Have you tried reinstalling the libnitrokey package?
