### ISSUE TITLE
No configure submenu available on macOS 10.13.5

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#368]
No configure submenu available on macOS 10.13.5.
It works on 10.12.6.
Connected: #366 

Edit: source: support email

**Comment by szszszsz** [comment]
Not reproducing on 10.13.2. Updating to 10.13.5.

**Comment by oderwat** [comment]
I can't reproduce that with my NitroKey Storage on 10.13.5 using app 1.3.

**Comment by szszszsz** [comment]
Thank you for confirming, @oderwat . I cannot either. I believe original reporter has been using the menu bar, and there indeed there is no `Configure` submenu. However, the one from the tray works as usual.
Closing. Will be reopened, if further details from the reporter would change the situation.
