### ISSUE TITLE
nitrokey base has trouble loading.

### ISSUE THREAD

**Issue by FrostKnight** [Nitrokey/nitrokey-app#374]
- 1.2 Backports/1.31 AppImage
- Operating system: [Hyperbola 0.2 64 bits, Linux-libre 4.9-110
- Storage v0.52
- Connected USB port type: 2.0
- Issue occurrency: always

This is going to sound extremely odd, but my nitrokey storage looks fine physically, but for some strange reason, the 2.1 GB volume is broken and here is the even stranger part:

**The 62GB volume loads fine without errors.**

This isn't a huge issue, but I would like to know if there is a way to undo the damage/if  this will be a bigger issue in the future

it simply won't mount for some reason... the below log should give some info:

Error mounting /dev/sdb at /run/media/fuser/9a89f525-4789-436c-8185-b5702c1c1c11: Command-line `mount -t "ext4" -o "uhelper=udisks2,nodev,nosuid" "/dev/sdb" "/run/media/flames/9a89f525-4789-436c-8185-b5702c1c1c11"' exited with non-zero exit status 32: mount: /dev/sdb is write-protected, mounting read-only
mount: wrong fs type, bad option, bad superblock on /dev/sdb,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

**Oh and also, I should mention, My other nitrokey storage 64GB doesn't have this problem whatsoever.**  **Same everything except for the firmware although, I had this problem before I upgraded the firmware. Even with 0.51 firmware for nitrokey storage. **

**Comment by szszszsz** [comment]
Hi! Sorry for confusion. UV is set to be read only by default in firmware
v0.52. Please use Nitrokey App to change that (see configuration menu).

niedz., 1.07.2018, 05:36 użytkownik FrostKnight <notifications@github.com>
napisał:

**Comment by FrostKnight** [comment]
Actually, it still does that even with 1.31 nitrokey-app.AppImage/Nitrokey-app 1.2 backported fix.  Although the 1.2 backported debian version does this weird thing where it claims the password I am typing in is incorrect, when it actually it is the password.

So yeah, there seems to be something odd happening.  I cannot say what, but I am guessing its the firmware. I don't dare upgrade my other key yet for fear of having the same crap happen.

**Comment by szszszsz** [comment]
Only Nitrokey App v1.3.1 supports Storage v0.52 fully. Older versions of the App might work improperly. In this case v1.2 calls unsupported command in latest firmware, hence device returns `wrong password` message, even when the PIN is correct.
Please use v1.3.1 to change the Unencrypted Volume's state to read-write to avoid issues mentioned earlier.
Regarding error - simply the read-only volumes are not handled correctly by your window manager. It should mount without any issues. The message actually states that it was successfully mounted.

**Comment by szszszsz** [comment]
Closing as explained. In case you would have further questions please write.
I have updated the [release description](https://github.com/Nitrokey/nitrokey-storage-firmware/releases/tag/V0.52) for the Storage firmware as well to avoid further confusion.
