### ISSUE TITLE
Latest Snap build (20) is not connecting to the device

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#379]
- Application version: v1.3.1
- Operating system: Ubuntu 18.04, Fedora 28
- Distribution channel: Snap
- Device model and firmware version: Storage v0.52
- Issue frequency: always

### Expected behaviour
Should connect, as previous release, `19`.

### Current behaviour
Not connecting to the device.

### Steps for reproduction
Install current release with `--devmode`, as guide states.

**Comment by szszszsz** [comment]
CC @alex-nitrokey

**Comment by szszszsz** [comment]
Started to work after further retesting. Perhaps some issue with Udev rules files?

**Comment by alex-nitrokey** [comment]
Let me know, if I can retest something.

**Comment by szszszsz** [comment]
Could you check please latest snap package, 21? 
It works for me on Ubuntu 18.04.

**Comment by alex-nitrokey** [comment]
I only get it working with sudo rights on my VM on which no modifications were made.

**Comment by szszszsz** [comment]
I see. How have you installed/updated it?

**Comment by alex-nitrokey** [comment]
```sudo snap install nitrokey-app --devmode```
When installing it states that it is downloading (21) - which should be the version number, right?

**Comment by szszszsz** [comment]
Yes, `21` is the current version.
So to confirm, even with the `--devmode` switch it is not working for you? In that case Udev rules might be indeed the culprit. Would installing `scdaemon` help?

**Comment by alex-nitrokey** [comment]
Okay, my fault. After installing scdaemon it helps to unplug and plugin again the Nitrokey :wink: sorry.

So yes, installing scdaemon does the trick, so probably something about udev rules? They are in the snap folder though...

**Comment by szszszsz** [comment]
This one is not occurring lately. More for completeness:
1. Current installation switch is `--classic` AFAIR.
2. The udev rules are included inside the package, however they are not available to system udev service. We would need to copy it outside of the isolated snap space to make it work automatically. We could think about this one in the future.

Closing as done.
