### ISSUE TITLE
Nitrokey is not detected under Windows

### ISSUE THREAD

**Issue by alexwh** [Nitrokey/nitrokey-app#380]
- Application version: v1.3.1
- Operating system: Windows 10 Insider version 1803 build 17713.1000
- Device model and firmware version: Storage v0.50
- Connected USB port type: 2.0
- Issue occurrency: always

### Current behaviour
When the device is plugged in on Windows, the Nitrokey App does not detect the key and remains in "Idle" state. The unencrypted partition and smartcard functionality works fine, and the nitrokey-update-tool detects the Nitrokey as being in production mode. In addition, the Nitrokey App works on Linux.

Logs attached: 
[debug-file.txt](https://github.com/Nitrokey/nitrokey-app/files/2247855/debug-file.txt)
In this log, the device was plugged in, Nitrokey App started, then the device was removed and reinserted.

**Comment by szszszsz** [comment]
Hi! Thank you for the report. 
Could you tell has the issue occurred with the recent OS update?

If you would confirm that, then I would search for the issue in the underlying `hidapi` library (a `libusb` wrapper), through which the USB communication is handled. Update Tool counts active devices using `libusb` directly (without connecting to though), hence it detects the device mode correctly. 
I remember there was a similar issue in the past with Windows 10, where the device class string ID was renamed on the OS side and made the device's unavailable to connect to.

**Comment by alexwh** [comment]
I believe the issue started happening some time in the last month or so. Where should I start to begin debugging the hidapi library? Is there some form of sample application I can test or logs I can view?

**Comment by szszszsz** [comment]
Hi @alexwh !
I am really sorry for the long delay. I plan to fix this in the coming week. Is the issue still occurring after last Windows updates?

**Comment by m-d-johnson** [comment]
I am seeing the same but I'm on latest Win 10 (1809) build 17763.107 and using a NK Pro 2.  Device manager shows  "Unknown Smartcard"

**Comment by jans23** [comment]
"Unknown Smartcard" is to be expected and is ok as long as you don't want to use the device with Microsoft tools.

**Comment by szszszsz** [comment]
Hi!
We have published today a new tool for users of Windows 10 1809 (and newer), and Storage v0.52 (and older). It is a bootable image, which allows to unlock the Storage device update feature. The guide for using it is located here: [Using the bootable image]. This should be a one-time operation, to allow to flash firmware v0.53, using which device can communicate under Windows 10 1809. Further updates will be possible to run with the Nitrokey Update Tool, as in the [main firmware update guide].

[Using the bootable image]: https://github.com/Nitrokey/nitrokey-storage-update-boot/blob/master/boot-image-usage-guide.md
[main firmware update guide]: https://www.nitrokey.com/en/documentation/firmware-update-storage

**Comment by szszszsz** [comment]
Fixed by changes in the firmware. Details:
- https://github.com/Nitrokey/nitrokey-pro-firmware/issues/50
- https://github.com/Nitrokey/nitrokey-storage-firmware/pull/74

Related:
- https://github.com/Nitrokey/nitrokey-app/issues/392
