### ISSUE TITLE
Win10 build1809: device is not recognized

### ISSUE THREAD

**Issue by alex-nitrokey** [Nitrokey/nitrokey-app#392]
- Application version: 1.3.2
- Operating system: Windows 10, build 1809
- Device model and firmware version: Storage 0.52
- Issue occurrency: always

### Current behaviour
device is not detected anymore due to a system update

### Steps for reproduction
update (or don't) to newest win10 version (build1809)

**Comment by alex-nitrokey** [comment]
I had to use insider preview, but I think the build is rolling out for all user already.

**Comment by espoelstra** [comment]
They paused the rollout of this update due to it deleting user data, not sure when they will resume the rollout.

**Comment by Free-name** [comment]
Same problem here:  Nitrokey is not connected

App version 1.3.2
Windows 10 build 1809 (i still have my files)

**Comment by szszszsz** [comment]
Fix is in progress.
cc @NKelias

**Comment by szszszsz** [comment]
Copying comment from https://github.com/Nitrokey/hidapi/pull/2#issuecomment-439989039: 
> Hi! We have found the cause and are finishing the working solution. It should be ready promptly.
Update will be posted then.

**Comment by dexterg33** [comment]
Hi, so what's the solution for 1809 users only? Should I wait, or upgrade firmware trough linux for example?

**Comment by alex-nitrokey** [comment]
You can either wait for our solution for windows users or indeed just boot into linux and upgrade there to [0.53](https://github.com/Nitrokey/nitrokey-storage-firmware/releases) if you prefer.

The windows solution might be published these days, but I can not say for sure. We are currently testing and improving the solution.

**Comment by cytec** [comment]
so... any news on this? it's been like a month and some people need to get back to work…

**Comment by szszszsz** [comment]
Hi!
We have published today a new tool for users of Windows 10 1809 (and newer), and Storage v0.52 (and older). It is a bootable image, which allows to unlock the Storage device update feature. The guide for using it is located here: [Using the bootable image]. This should be a one-time operation, to allow to flash firmware v0.53, using which device can communicate under Windows 10 1809. Further updates will be possible to run with the Nitrokey Update Tool, as in the [main firmware update guide].

[Using the bootable image]: https://github.com/Nitrokey/nitrokey-storage-update-boot/blob/master/boot-image-usage-guide.md
[main firmware update guide]: https://www.nitrokey.com/en/documentation/firmware-update-storage
