### ISSUE TITLE
App crashes when retrieving authenticated OTP code from locked device

### ISSUE THREAD

**Issue by NKelias** [Nitrokey/nitrokey-app#394]
- Application version: 1.3.2
- Operating system: Tested on Arch Linux 4.18.9 and Windows 10 64bit build 1803
- Device model and firmware version: NK Storage v0.52 with merged PR https://github.com/Nitrokey/nitrokey-storage-firmware/pull/73 (firmware attached)
- Connected USB port type: 3.0
- Issue occurrency: always

Firmware: 
[firmware_v052_pr73.zip](https://github.com/Nitrokey/nitrokey-app/files/2476794/firmware_v052_pr73.zip)

### Expected behaviour
Prompt user for User PIN

### Current behaviour
App crashes with message
```
Critical error encountered. Please restart application.
Message: Command execution has failed on device
```

#### Preconditions
- OTP codes protected by user password

#### Steps
1. Unlock device by using `Unlock Password Safe` function via app
2. Retrieve OTP code from device (successful)
3. Lock Device by using `Lock Device` function via app
4. Retrieve OTP code from device (fails)

### Logs

Logs attached: 
[nk.log](https://github.com/Nitrokey/nitrokey-app/files/2476791/nk.log)

**Comment by szszszsz** [comment]
Should be fixed with 1.5 release
