### ISSUE TITLE
NK is not recognized (Linux and Windows)

### ISSUE THREAD

**Issue by martin-mmmm** [Nitrokey/nitrokey-app#401]
- Application version: 1.2.1 (Linux) 1.3.2 (Windows 10)
- Operating system: Linux Mint 19 and Windows 10 (different PCs)
- Device model and firmware version:Start, cant say fw-version, since i cant read it, NK was bought two days ago, so i guess the current one.
- Connected USB port type: 2.0 and 3.0 both tried on both systems
- Issue occurrency: always

### Expected behaviour
App should recognize NK

### Current behaviour
the NK is not recognized by the Nitrokey app, neither under Linux nor under Windows. Kleopatra recognizes the stick and with gpg a key could be written on the stick. 

### Steps for reproduction
Insert the key in any usb-port

#### Preconditions
None, the app can be just started or already running for an hour, the stick can be connected before starting the app or afterwards, it makes no difference.

### Logs
From Linux machine

Logs attached: 
- 
[debug-file.txt](https://github.com/Nitrokey/nitrokey-app/files/2773748/debug-file.txt)

**Comment by szszszsz** [comment]
Hi @martin-mmmm !

Nitrokey Start is not managed by the Nitrokey App. It provides only the smart card service via the CCID interface. In the future it is planned to provide basic information about all the devices in the Nitrokey App, even if there would be nothing more of use to.

Sorry for the confusion.

@alex-nitrokey @jans23 Could we add a note to Nitrokey Start device's page about this?

**Comment by szszszsz** [comment]
Firmware version of the Nitrokey Start should be available via the Kleopatra / gpg2, in the serial number field, as far as I remember.

**Comment by alex-nitrokey** [comment]
Mh, it is stated on the download page at least https://www.nitrokey.com/download

:thinking:  I am not sure how to make this more clear without adding it to every device which is not supported. (counts for HSM and FIDO U2F too).

**Comment by martin-mmmm** [comment]
Oh no! Shame on me!
Sorry for wasting your time, i installed the app even before i decided which version i would like to buy.

@alex-nitrokey , it would be more clear if the app recognizes the Key and let you know that it is not supported by the app / not necessary to use it with the app. atm it says "no active nitrokey* which could be confusing. (like it did with me :-) ) 

Thank you for your kind replies!

**Comment by alex-nitrokey** [comment]
> @alex-nitrokey , it would be more clear if the app recognizes the Key and let you know that it is not supported by the app / not necessary to use it with the app. atm it says "no active nitrokey* which could be confusing. (like it did with me :-) )

That's totally right. We even plan to support in some ways in the feature (e.g. changing PIN), but it is no priority yet.

**Comment by alex-nitrokey** [comment]
And no worries about "wasting our time". Help/suggestions etc. is always appreciated!
