### ISSUE TITLE
Make it nicer - same method for transaltion selection

### ISSUE THREAD

**Issue by Peacekeeper2000** [Nitrokey/nitrokey-app#409]
the translation file could be choosen by a pull down. For German it is "de_DE" as an entry, whiel for other langguages iut is only "en" or "fr" - so it should be either "de" or "en_US" and "en_UK"
etc. Currently that - and yes it is more a polishing of the UI - is distracting

- Application version: [1.3.2]
- Operating system: [macOS, 10.14.4, 64 bits]
- Device model and firmware version: [Storage v0.53 ]
- Connected USB port type: [3.0]
- Issue occurrency: [always]

**Comment by jans23** [comment]
Since we don't have any localization other than the language itself (no point to distinguish en_UK from en_US for example) I suggest to make it "Deutsch", "English", "Français" etc.

**Comment by Peacekeeper2000** [comment]
I just wonder where the translation files are under macOS. I would have expected them under ....Content/resources/... of the App. But it looks like they are compiled into the App ??
Anyhow, I think a constant way of naming would be prefferable and doing it with ISO labels sounds good for me - just in the same way for all

**Comment by szszszsz** [comment]
Yes, they are internal resource, as specified in https://github.com/Nitrokey/nitrokey-app/blob/master/resources.qrc#L7. Renaming should not be a problem.
The double naming came from initial assumption, that the ISO codes would be kept.
