### ISSUE TITLE
Check new translations 

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#41]
Check new translations introduced  by pull #25 .
They are merged as were (they overwritten current one) in branch pull_25_translations.

**Comment by jans23** [comment]
I committed translations to branch pull_25_translations:

**Comment by szszszsz** [comment]
Hi @jans23 ! 
Please check `pull_25_translations_2` branch. I have rebased code on master, updated translation files, so some new entries have appeared. Also `Change Firmware Password` is not translated to German.

**Comment by jans23** [comment]
I updated the translation. Please verify the English text for the following:

# It's user and admin PIN, not password.
# It's firmware password, not PIN.
# The note that PINs don't need to be long does only apply for user and admin PIN but not for firmware password.

Please search for "password" and fix it accordingly.

**Comment by szszszsz** [comment]
Done.
It is now possible to change UI strings for English directly with QT Linguist without source code change.
