### ISSUE TITLE
Add support for Nitrokey Pro Firmware Update command

### ISSUE THREAD

**Issue by NKelias** [Nitrokey/nitrokey-app#418]
### Expected behaviour

User shall be able to initiate a Device Firmware Update operation by issuing the newly introduced [CMD_FIRMWARE_UPDATE]. The command expects the Firmware Update Password as a null-terminated ASCII String and returns `CMD_STATUS_WRONG_PASSWORD` if the password was incorrect. Nothing is returned on successful execution. This behavior is identical to the Nitrokey Storage Firmware Update functionality.

[CMD_FIRMWARE_UPDATE]: https://github.com/NKelias/nitrokey-storage-firmware/blob/5e617988c012f9425b5edd92862a6159e12d3afb/src/inc/report_protocol.h#L49

**Comment by szszszsz** [comment]
Fixed with 6e4e75ff1beec672ec46af34b33264848a83550e
