### ISSUE TITLE
Activate features of '--admin' flag via checkbox in App

### ISSUE THREAD

**Issue by alex-nitrokey** [Nitrokey/nitrokey-app#419]
It should be possible to activate the features nowadays activated by `--admin` flag via the App GUI as well. Otherwise, people need to know how to use the cli. As the function "Factory reset" is a valid function for users, this would help them to debug their device without _scary_ command line.

**Comment by jans23** [comment]
Why is factory reset useful for ordinary use cases?

**Comment by szszszsz** [comment]
I think Alex was referring to cases, where users wants the factory defaults on the device after some phase of experimentation with the device [1].

[1] https://support.nitrokey.com/t/is-my-nitrokey-a-brick-now/1802/6

**Comment by alex-nitrokey** [comment]
> I think Alex was referring to cases, where users wants the factory defaults on the device after some phase of experimentation with the device [1].

Yes, I got once more a user request and realized that it would make sense.

Actually, I would even suggest to enable factory-reset in terms of the GnuPG feature, where no admin pin is needed at all. Currently we have [6 option for factory-reset](https://www.nitrokey.com/documentation/frequently-asked-questions-faq#how-to-reset-a-nitrokey) and the App (option 1) only allows it when admin PIN is provided. 

It would be way more simple, if we could refer to the App, if someone blocked the card. Some more warnings what the option actually does may be a good idea in this case. (sorry for expanding the scope a bit by this comment)

**Comment by jans23** [comment]
The "--admin" mode has more implications than just the factory-reset command, but I don't remember the details. All implications should be first described before deciding on a solution.

**Comment by szszszsz** [comment]
@jans23 Leaving the `--admin` mode aside, what do you think about the PIN-less factory reset?

**Comment by jans23** [comment]
I think a checkbox in the GUI to enable the --admin mode would be good. 
Only in the admin mode the PIN-less factory reset should be possible. 
That should require the user to enter a text string as a confirmation, 
such as "Enter RESET to irreversibly reset the Nitrokey device".

**Comment by alex-nitrokey** [comment]
> Only in the admin mode the PIN-less factory reset should be possible.

I do not think so. A user can only reset the device via command line tools if the admin PIN is not known anymore and there is no reason for this precation imho. The purpose of a factory reset is to be able to, well, reset the device without the need of anything.

> That should require the user to enter a text string as a confirmation,
such as "Enter RESET to irreversibly reset the Nitrokey device".

This is a good idea!

Please let us include an option to easily factory-reset within the App without any cli usage. The current situation is unnecessary difficult for general users and causes problem every now and then. If this replaces the `--admin` or not is not important for me.

**Comment by szszszsz** [comment]
Recently I have changed the behavior to have it always visible (without adding an additional checkbox):
- https://github.com/Nitrokey/nitrokey-app/commit/6e5367cf1b465442c989bcd58996b15948715f64

In case you do not agree with this solution let me know, and reopen this ticket.
