### ISSUE TITLE
Implement better detection of unpartitioned encrypted volume

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#42]
Implement better detection of unpartitioned encrypted volume. Currently it is checked through existence of a symlink /dev/nitrospace (created by udev, pull #25). It might be better to check it reading /proc (which is already implemented).

**Comment by Belatronix** [comment]
Use the force Luke! 
And this force are kernel triggered udev events. What is the reason to reinvent the wheel? Udev was developed exactly for this.

**Comment by szszszsz** [comment]
Hi Belatronix!

After reconsideration I think you are right. Checking through udev could be the best method. However I would like to test it more to ensure all cases are covered. I will close the issue for now to not clutter the view and reopen in case I would have any suggestions. Thanks for your work!
