### ISSUE TITLE
No light icon available for dark trays

### ISSUE THREAD

**Issue by Segaja** [Nitrokey/nitrokey-app#425]
- Application version: v1.4
- Operating system: Archlinux x64
- Issue occurrency: always

### Expected behaviour
Have a visible tray icon if you use a tray with black background color.

### Current behaviour
You don't see the icon, because the icon is black and the background of the tray bar is also black.

### Steps for reproduction
Start the app with icon active on a black tray bar.

**Comment by anthraxx** [comment]
something like a gradient based icon instead of solid colors would work in basically all environments.

**Comment by szszszsz** [comment]
@Segaja Thank you for the report! Will take care of it on the next release.

@anthraxx Good idea, but I think it will not look good. Maybe we should consider moving back to red color by default, and allow later to choose white or black.

**Comment by jans23** [comment]
Other applications face the same challenge. Perhaps worth looking how they solved it.

**Comment by Segaja** [comment]
I don't want to push, but may I ask what the ETA is for the next release?

**Comment by szszszsz** [comment]
The plan is to work on it and release next month. Perhaps it would be possible to release some small fixes earlier (like this issue).

**Comment by Segaja** [comment]
So it has been three month now and I still don't see a release for this... 

Any idea when we can see this live?

**Comment by alex-nitrokey** [comment]
Same goes for other OSs, of course. Just wanted to mention.
https://support.nitrokey.com/t/bug-nitrokeyapp-icon-invisible-in-windows-10-dark-mode/2424

**Comment by Segaja** [comment]
I guess it is a general issue for dark themed desktop environments.

**Comment by Segaja** [comment]
So there recently was a new release: [1.4.1](https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.4.1).

Why wasn't this included in that release?
