### ISSUE TITLE
Warn user about bad AES when TOTP is set up

### ISSUE THREAD

**Issue by alex-nitrokey** [Nitrokey/nitrokey-app#429]
- Application version: 4.0
- Operating system: all
- Device model and firmware version: Storage 0.54
- Issue occurrency: always

### Expected behaviour
If a user creates a TOTP she/he should get warned about broken AES key, like it is the case when encrypted volume is opened (see error message discussed here #264).

### Current behaviour
The user is not warned about bad AES key so that she/he may set up the whole device including TOTP keys and only realizes the necessity of hitting "destroy encrypted data" button afterwards and thus needs to set up TOTP keys again.

**Comment by szszszsz** [comment]
AFAIR the AES key should be generated on the EV/PWS setup automatically, but will check that.

- [ ] make sure the AES key is generated, and device is initialized, before TOTP use

**Comment by szszszsz** [comment]
Closing as `wontfix` for now, as OTP flash space is not encrypted at the moment, thus AES key is not required. This might change in the future.
