### ISSUE TITLE
The tray icon isn't displayed

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#43]
The tray icon isn't displayed
Similar issue occurred before:
https://www.assembla.com/spaces/cryptostick/tickets/99-tray-icon-is-displayed-at-wrong-corner-of-the-screen/details#

OS Ubuntu 15.10 Unity - cannot use app at all (cannot run context menu), compiled using qmake
OS Ubuntu 15.04 Gnome (Version: 3.14.4-0ubuntu1), icon is not displayed but its docked (one just click on empty space to run context menu),  compiled through both cmake and qmake, not installed

**Comment by jans23** [comment]
This issue is solved for me on Ubuntu 16.04. Because 16.04 is the latest LTS it is the version we should focus on. Please reopen if it happens for you with 16.04 but not with an earlier version of Ubuntu.

**Comment by jans23** [comment]
The issue is still valid for me with Ubuntu 16.04 and Unity.

**Comment by szszszsz** [comment]
Hi! 
Was the icon shown at first (right after installation) and now disappeared?

**Comment by jans23** [comment]
Initially I was testing with the latest NK App _release_ which works
fine under Ubuntu 16.04. When I compile the latest master the issue
happens even with Ubuntu 16.04. So we might fix it by either trying to
compile the App under Ubuntu 15.04 or the issue got reintroduced into
our code somewhere between the last release and today.

>

**Comment by jans23** [comment]
A workaround is ```sudo apt-get remove appmenu-qt5``` which works fine for me. 

Owncloud client has the same problem as our App. [4693](https://github.com/owncloud/client/issues/4693), [1511058](https://bugs.launchpad.net/ubuntu/+source/owncloud-client/+bug/1511058)

The root cause seems to be in appmenu-qt5 [1574699](https://bugs.launchpad.net/appmenu-qt5/+bug/1574699).

Most interestingly, owncloud has a [workaround](https://github.com/owncloud/client/commit/0da2adcbe02eb9499e90622ca60a726ba75d0188) implemented. Maybe we could implement this too?

**Comment by szszszsz** [comment]
Fix working on Ubuntu 16.04.
Please check merge comment for more information.

**Comment by jans23** [comment]
It works for me. Great.

**Comment by DroWnThePoor** [comment]
Icon disappeared with yesterdays update, got another update today but nothing has changed.
I really need this to work as ownCloud is a huge part of my workflow, and being able to passively see that changes to code are being synced is a huge advantage here.
Elementary OS Freya ownCloud-Client: Version 2.2.0%nil (build 1605)

**Comment by szszszsz** [comment]
Hi @DroWnThePoor!
I believe you have posted this issue to the wrong project. Please check https://github.com/owncloud/client/issues/4693
