### ISSUE TITLE
Working build on FreeBSD

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#449]
Make it possible to run build on FreeBSD out of the box.
Details: https://support.nitrokey.com/t/using-the-nitrokey-app-under-freebsd/889/13

**Comment by Maurozio** [comment]
I have a dream! to have nitrokey-app in freebsd port lol

**Comment by szszszsz** [comment]
Hi!

Thanks to @monwarez it should build now! Let me know how it works, and what to improve next (perhaps reopen).
