### ISSUE TITLE
missing signature artifacts on github release for v1.4.1

### ISSUE THREAD

**Issue by anthraxx** [Nitrokey/nitrokey-app#451]
The release v1.4.1 on the github release page is missing all the signature artifacts that all other releases have.

Please distribute the signature etc files like previous releases as we use those to build for our distro.

cheers,
Levente

**Comment by szszszsz** [comment]
Hi Levente!

Indeed this are missing, thank you for the report. It should be corrected in the coming 2 working days.

**Comment by anthraxx** [comment]
Guess something came in between? :cat:

**Comment by szszszsz** [comment]
Yes, sorry! Thank you for bumping this up!

**Comment by anthraxx** [comment]
@szszszsz another gentle bump? :joy_cat:

**Comment by szszszsz** [comment]
Signed archive added to https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.4.1.
Thanks for keeping eye on that!

**Comment by anthraxx** [comment]
@szszszsz awesome, time to release the distro package. thanks a lot :heart:
