### ISSUE TITLE
bash-completion file can end up being installed into /usr/etc/

### ISSUE THREAD

**Issue by Polynomial-C** [Nitrokey/nitrokey-app#453]
Steps to reproduce:

- Make sure you don't have a `bash-completion.pc` file installed
- run cmake with `-DCMAKE_INSTALL_PREFIX=/usr` (this is what Gentoo ebuild is doing)

Result:

bash-completion file gets installed into `/usr/etc/bash_completion.d/`

Possible solution:

Let this be overridable by setting (for example) `-DBASH_COMPLETION_DIR="/some/path"` and only do your path magic when this has not been set by the user.

**Comment by szszszsz** [comment]
Hi @Polynomial-C !

Thank you for the report! It should be fixed now thanks to @SoapGentoo, with #454. Do you need a quick release for that?

**Comment by SoapGentoo** [comment]
@szszszsz quick release would help us, then I can quickly add it and remove the patches

**Comment by szszszsz** [comment]
Noted! Should be done in next 24h.

**Comment by szszszsz** [comment]
Done at https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.4.2
Sorry for the delay!

**Comment by SoapGentoo** [comment]
Thanks a lot for being so responsive to our requests!
