### ISSUE TITLE
Jobs failing on Travis-CI during build

### ISSUE THREAD

**Issue by kishorkunal-raj** [Nitrokey/nitrokey-app#458]
Hi All,
Jobs failing during travis-ci build on OSX platform. Detailed log:

==> java has been moved to Homebrew.
To uninstall the cask run:
  brew uninstall --cask --force java
==> Installing java...
Warning: You are using macOS 10.12.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
==> Downloading https://github.com/openjdk/jdk/commit/f80a6066e45c3d53a61715abfe
######################################################################## 100.0%
==> Downloading https://github.com/openjdk/jdk/commit/4622a18a72c30c4fc72c166bee
######################################################################## 100.0%
==> Downloading https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb1
######################################################################## 100.0%
==> Downloading https://hg.openjdk.java.net/jdk-updates/jdk15u/archive/jdk-15.0.
######################################################################## 100.0%
Warning: Your Xcode (8.3.3) is outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store or run:
  softwareupdate --all --install --force
If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install
Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
==> Patching
==> Applying f80a6066e45c3d53a61715abfe71abc3b2e162a1.patch
patching file src/hotspot/share/runtime/sharedRuntime.cpp
Hunk #1 succeeded at 2850 (offset -6 lines).
==> Applying 4622a18a72c30c4fc72c166bee7de42903e1d036.patch
patching file src/java.desktop/macosx/native/libawt_lwawt/awt/CSystemColors.m
==> ./configure --without-version-pre --without-version-opt --with-version-build
==> make images
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

Detailed log can be found @ https://www.travis-ci.com/github/kishorkunal-raj/nitrokey-app/jobs/460468324

Please look into it and help me with the fix

**Comment by szszszsz** [comment]
Hi!
The image for the macOS has to be updated to the next one, and this one removed, as it is not supported by the Homebrew anymore. Could you look into this?
By the way, why the Java is updated here? I guess this is some general update run.

**Comment by kishorkunal-raj** [comment]
Thank you for the opportunity you offered but I am sorry to say that it doesn't comes under my area of expertise.
