### ISSUE TITLE
Cannot build from source,

### ISSUE THREAD

**Issue by FrostKnight** [Nitrokey/nitrokey-app#459]
Nitrokey-app 1.4.2 and 1.4.1 do not build from source with make,
I have used both qmake and cmake methods and both times it gives me some weird error:

../src/ui/mainwindow.cpp:505:34: fatal error: cppcodec/hex_upper.hpp: No such file or directory
 #include <cppcodec/hex_upper.hpp>

I have all libraries that I know of... except maybe catch2, not sure if that's needed or where that goes in the files if it is needed.

- Issue  always

 Expected behaviour

I can build 1.4.0 easily, its just 1.4.1 and past...

Are the tar.gz/tar/zips and source code missing certain things?

Still using Hyperbola, in a few months it will upgrade a bunch of things to more updated packages, 

Although I am curious why versions  1.4.0  and before I can build easily enough but not 1.4.1 or 1.4.2.

Is there any benefit to updating?

**Comment by szszszsz** [comment]
Hi!
This looks like the submodules were not initialized. Could you run the below in the root directory and check again?
```
git submodules update --init --recursive
```

**Comment by FrostKnight** [comment]
I just tried both in the root directory and the build directory, neither worked.  Although, git was being a bit odd, and submodules wasn't a command, submodule was however... and that didn't seem to work either.  

got this error though anyways: 

fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DIS[user@host[user@user nitrokey-app]$ git submodule update --init --recursive

Tried a few times now, I am a bit confused though.

**Comment by szszszsz** [comment]
Indeed it should have been `submodule`.
I see. You need to clone this repository to build the application since the zip archive with the source code does not contain the git submodules.

Please try this one:
```
git clone https://github.com/Nitrokey/nitrokey-app.git --recursive
```

**Comment by FrostKnight** [comment]
Ah, thank you, yes I have almost everything fixed at the moment... 
Now I just need to track down why this happened:  
error while loading shared libraries: libhidapi-libusb.so.0: cannot open shared object file: No such file or directory

Odd it is, since I have hidapi installed. hmm... so far so good though!

**Comment by FrostKnight** [comment]
Nevermind, I got it now, hidapi's newer version has some conflicts at the moment...  I used my distro's older one and it works. Solved I would say.
