### ISSUE TITLE
bad fixed window size for low resolutions, ui elements inaccessible

### ISSUE THREAD

**Issue by Discordia42** [Nitrokey/nitrokey-app#465]
- Application version:1.4
- Operating system:Qubes OS
- Device model and firmware version: thinkpad x230
- Issue occurrency: always(except in fullscreen)

### Expected behaviour
The window adapting to the screen size and resolution fitting all UI elements on screen at the very least down to 720p.

### Current behaviour
The lower border of the Window and the save buttons for passwords, OTP etc get cut off and are inaccessible.

### Steps for reproduction
1. install qubes os on an x230
2. install the nitrokey-app on a template
3. open a domain using the template
4. open the nitrokey app

#### Preconditions
720p screen or lower.

**Comment by szszszsz** [comment]
Hi!
This should be solved by v1.4.1:
- https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.4.1

We are sorry about not being easily accessible yet (like through Snap). How have you installed v1.4?

**Comment by Discordia42** [comment]
through the fedora and debian package manager specifically the respective template VMs.

**Comment by szszszsz** [comment]
According to below it should be distributed already over all major Linux distributions. Closing as done.
- https://repology.org/project/nitrokey-app/badges
- https://pkgs.org/download/nitrokey-app

![image](https://user-images.githubusercontent.com/17005426/129444418-0712787e-9fe0-4f07-ab7f-0babf4773c11.png)
