### ISSUE TITLE
No "Destroy encrypted data" menu entry

### ISSUE THREAD

**Issue by to-huu** [Nitrokey/nitrokey-app#466]
- Application version: 1.3.2
- Operating system: NixOS, 64bit, Kernelversion 5.4.93
- Device model and firmware version: Pro v0.10
- Connected USB port type: 3.0
- Issue occurrency: always

### Expected behaviour
After doing a factory-reset with gpg2 there is a "Destroy encrypted data" entry under Menu -> Configure. 
### Current behaviour
There is no such entry. Only "OTP and Passwordsafe", "Change User pin", "Change Admin Pin" and "Factory Reset".

**Comment by szszszsz** [comment]
Hi!
Sorry for the delay. 

Can you check running Nitrokey App with  `--admin` switch?

**Comment by to-huu** [comment]
No Problem. It's the same with the `--admin` switch.

**Comment by szszszsz** [comment]
I see, thank you for checking. I will work on this in the next days, and retest on the v1.4.0 as well.

**Comment by szszszsz** [comment]
Hi!
This menu entry will be shown now for the Nitrokey Pro starting from the very next release (with a `--admin` switch set).
