### ISSUE TITLE
Nitrokey 3 support?

### ISSUE THREAD

**Issue by bordenc** [Nitrokey/nitrokey-app#491]
I completely understand from https://docs.nitrokey.com/nitrokey3/linux/ that "Currently the Nitrokey App can not be used for the Nitrokey 3." I assume that this is a work in process and will be implemented when far more pressing issues are resolved.

However, from a high level, what issues need to be resolved for the app to support NK3s? What can people who have general programming competency, but no familiarity with the NK3 hardware, do to assist?

**Comment by jans23** [comment]
The current Nitrokey App won't support Nitrokey 3. Instead we plan to release [Nitrokey App 2](https://github.com/Nitrokey/nitrokey-app2/) later this year which solely supports Nitrokey 3. It's written in Python and you are welcome to contribute.

**Comment by bordenc** [comment]
@jans23 will this be an official successor to Nitrokey App (1) that will support all NK versions?

**Comment by jans23** [comment]
NK App 2 will focus on Nitrokey 3 devices for now. It is not decided yet, if we will add support for other Nitrokey models in the future.
