### ISSUE TITLE
provide writeToHOTPSlot as shared library

### ISSUE THREAD

**Issue by cornelinux** [Nitrokey/nitrokey-app#5]
I would like to write the OTP Slots from [another application](https://github.com/privacyidea/privacyideaadm), to be able to initialize an OTP slot and send the OTP secret to the [backend](https://github.com/privacyidea/privacyidea) the same time. Thus noone needs to generate or copy an OTP secret manually.

I see writing the slots is performed [here](https://github.com/Nitrokey/nitrokey-app/blob/master/src/device.cpp#L582) but I do not want to duplicate the code.

So a shared library which would provide a function like

    writehotpslot(slotobject, adminPIN)

would be great.

**Comment by jans23** [comment]
[Here](https://github.com/Nitrokey/libnitrokey) is an early version of the library. Work in progress.
