### ISSUE TITLE
NK Storage: Erasing HOTP slot results in LED staying red on Nitrokey

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#56]
After erasing HOTP slot in `OTP Slot Configuration` window LED on Nitrokey stays red until another erasing on TOTP would happen or `OTP Slot Configuration` window will reopen. Unlocking encrypted and hidden volumes also does not clear it.   

Nitrokey Storage
Ubuntu 16.04
Built using qmake . && make -j3

**Comment by szszszsz** [comment]
To investigate whether lit red LED is the only incorrect result of the operation

**Comment by jans23** [comment]
I changed the priority to high because this might require a firmware change.

**Comment by rudbo** [comment]
Fixed with
https://github.com/Nitrokey/nitrokey-storage-firmware/commit/0910a90ac84e86d148969181021874ecf4a70a8a
