### ISSUE TITLE
Warning displayed when unlocking an encrypted NTFS partition

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#58]
My encrypted volume contains a NTFS partition. When I unlock my volume the partition gets mounted automatically. A warning is displayed that my volume doesn't contain a partition and that I should use gparted or fdisk. This doesn't make sense.

**Comment by szszszsz** [comment]
Hi! 
The displayed warning is connected directly to processing udev rules. What OS were you using during the test? If it is Ubuntu, please check have you updated the udev rules file to latest.
The file is in repository under path  `nitrokey-app/data/40-nitrokey.rules` and should be copied under Ubuntu to `/etc/udev/rules.d/`

**Comment by szszszsz** [comment]
This the logic behind the warning message:
https://github.com/Nitrokey/nitrokey-app/commit/d1be976c20f803f56314230b963ee3c018991329

**Comment by szszszsz** [comment]
Hi @jans23 !
Could you let me know what OS were you using at a time issue has occured?

**Comment by jans23** [comment]
Ubuntu 16.04 with Unity.

**Comment by szszszsz** [comment]
Hi @jans23 
Unfortunately this issue is not reproducing on my laptop. I have single NTFS partition on encrypted volume and after unlocking it is mounted automatically. The warning about using fdisk is not shown.
Could you unlock your volume, run following commands and paste in output?

> sudo fdisk -l # list partitions
> ls -l /dev/nitro*

**Comment by jans23** [comment]
$ sudo fdisk -l 
Disk /dev/sdd: 27.7 GiB, 29767499264 bytes, 58139647 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x2052474d

Device     Boot      Start        End    Sectors   Size Id Type
/dev/sdd1          6579571 1924427647 1917848077 914.5G 70 DiskSecure Multi-Boot
/dev/sdd2       1953251627 3771827541 1818575915 867.2G 43 unknown
/dev/sdd3        225735265  225735274         10     5K 72 unknown
/dev/sdd4       2642411520 2642463409      51890  25.3M  0 Empty

Partition table entries are not in disk order.


Disk /dev/sdc: 2 GiB, 2147483648 bytes, 4194304 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x6e652072

Device     Boot      Start        End    Sectors   Size Id Type
/dev/sdc1       1768187213 3469398961 1701211749 811.2G 6e unknown
/dev/sdc2       1953723749 2934433733  980709985 467.7G ff BBT
/dev/sdc3       1801683314 1970335702  168652389  80.4G 74 unknown
/dev/sdc4       2885681152 2885735363      54212  26.5M  0 Empty


$ ls -l /dev/nitro*
ls: cannot access '/dev/nitro*': No such file or directory

**Comment by szszszsz** [comment]
Hi @jans23
Fdisk data shows that your partition table is either malformed or could be in another format than it could parse. The sectors count on the device and size in sectors of partitions (much bigger values) are not aligned. What tool have you used to create partitions table?
Please paste in the result of parted list with mounted encrypted volume:

> sudo parted -l # list partitions 

Please also compare following:

> $ ll /etc/udev/rules.d/40-nitrokey.rules 
> -rw-r--r-- 1 root root 1129 kwi 11 17:14 /etc/udev/rules.d/40-nitrokey.rules
> $ md5sum /etc/udev/rules.d/40-nitrokey.rules 
> 41cb771839dd01f915a98c9fda38414f  /etc/udev/rules.d/40-nitrokey.rules
> 


For comparing partition tables please check attachment.
 

[issue_58-fdisk_log.txt](https://github.com/Nitrokey/nitrokey-app/files/275789/issue_58-fdisk_log.txt)

**Comment by jans23** [comment]
I believe the root cause was a broken MicroSD storage.

**Comment by szszszsz** [comment]
It might be useful to add description of such situation to readme.
