### ISSUE TITLE
NK Storage: Changing Firmware Password doesn't work

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#71]

**Comment by szszszsz** [comment]
Hi @jans23 @rudbo ! 
Does the firmware password has its own retry count? I have not seen any while I wanted to display the counter to the user.

**Comment by jans23** [comment]
It doesn't has a retry counter. Its a kind of password.
-- 
Sent from a mobile device.

**Comment by rudbo** [comment]
App:
SHA-1: ab1ed5171acfd9890963ac09cc38da2efb622d44
Changing Firmware Password worked, but the app always display an error.
Now the stick is waiting for answer from stick
Stick:
SHA-1: 627ccaf139a4e6cbdb4d2334e410fa716c3980b8
* Send answer to app when entering the update modus

**Comment by jans23** [comment]
Still I can't change the Firmware Password. When I try to change the Firmware Password I get no positive or negative response at all. Afterwards the old password still works.

**Comment by rudbo** [comment]
https://github.com/Nitrokey/nitrokey-app/commit/5139cb95aead649958b3af94a710fc5cabbb9137
Wait for response to avoid fast sending next command that overwrite the last command

**Comment by szszszsz** [comment]
I will reopen for a moment. 
I have changed firmware password on my stick from 12345678 to other one and back to 12345678. There had to be some problem here though since I cannot enter into update mode on this device.
@jans23 : Could you enter into update mode on device you have tested? Could you reprogram it?

**Comment by szszszsz** [comment]
I have logged my second try to make sure it is not entry error. There was no error message shown. I have no debug log from app unfortunately.
```
Old:  "12345678"
New1:  "123123123"
New2:  "123123123"
==================================
Old:  "123123123"
New1:  "12345678"
New2:  "12345678"
```

**Comment by szszszsz** [comment]
Actually it has just went into update mode when retried after factory reset command. I have reinserted the device before and it was not switching to update mode.
