### ISSUE TITLE
Add guidelines for contributing

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#75]
Add CONTRIBUTING.md with:
- code style guidelines (code reformatting)
- git flow description
- make as small consisting changes as possible within one PR (eg. do not mix translations and functional changes)
- do not mix functional changes with not own code reformat 
- what issue description should contain (OS, stick firmware, app version)

**Comment by MaVo159** [comment]
-Compile without warnings (on at least one recent compiler version).
-Pass llvm-format without changes (use a style config file if necessary)
-Don't break ability to compile (at least on amd64)
Use travis to enforce these and to always have binary builds.

**Comment by szszszsz** [comment]
@jans23 @MaVo159 
Please check guidelines submitted in commit. Further additions should be made in `issue_75-contributing`. Please update in case of obvious errors in separate commits.

**Comment by MaVo159** [comment]
The .md contents sound pretty good. I didn't look at more stuff. I'm a little confused why there are 3 commits that add the same file (is it the same?). I'm on mobile, so it is difficult to check what is going on. Anyway, looks good to me.

**Comment by szszszsz** [comment]
Great! You can visualize it under [link](https://github.com/Nitrokey/nitrokey-app/blob/b8faba24530b0287b396c364f35e4f191fd63c09/CONTRIBUTING.md)
These are all same commit (technically different) on same branch - I have updated the content two times because of typos.
