### ISSUE TITLE
USB 3.0: Updating progress bar during clearing SD card is not working

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#76]
Dialog with progress bar hangs after 40 calls while clearing SD card with stick in USB 3.0 port. 
On USB 2.0 port it is working correctly.
Nitrokey storage, FW 0.31
Ubuntu 16.04, updated
Nitrokey-app, 37fa86ca7ca6850d25a91977aa2323af59e4dd87, debug mode

**Comment by jans23** [comment]
Please retest with latest Storage firmware v0.34.

**Comment by szszszsz** [comment]
Fixed with latest firmware 0.34, closing.
