### ISSUE TITLE
Only three passwords displayed

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#78]
When using Nitrokey App with Nitrokey Pro on Ubuntu 16.04 only the first three passwords are displayed, eventhough 16 are stored. All 16 are displayed well on Windows.

![passwords](https://cloud.githubusercontent.com/assets/1450547/15620095/7a4b8c1c-2458-11e6-942a-626d5990dbad.png)

**Comment by szszszsz** [comment]
Details:
- Password Safe
- Compiled with CMake and `HAVE_LIBAPPINDICATOR=ON`, g++ 5.3.1

When compiled with `qmake && make` all works.

**Comment by szszszsz** [comment]
Issue reproduced and fixed. Please reopen if it is not working for you.
