### ISSUE TITLE
Please push tag v0.2

### ISSUE THREAD

**Issue by KaiHa** [Nitrokey/nitrokey-app#8]
On the Nitrokey website (https://www.nitrokey.com/download) version 0.2 of the *nitrokey-app* is available. But In the repository I have not found the corresponding tag. Please push the tag *v0.2* so it is clear from which commit the released version was compiled.

Regards

**Comment by jans23** [comment]
Done. See https://github.com/Nitrokey/nitrokey-app/releases/tag/v0.2
