### ISSUE TITLE
Config backup

### ISSUE THREAD

**Issue by MaVo159** [Nitrokey/nitrokey-app#87]
Since the passwords and OTP-Keys stored on the Nitrokey are pretty important in some cases, it would be convenient to be able to back them up to a simple human readable (JSON?) file.

I am imagining something like (JSON, some OTP fields missing for readability):
```json
{
	"TOTP": [{
		"Name": "Google",
		"Key": "0xXXX"
	}, {
		"Name": "Amazon",
		"Key": "0xXXX"
	}],
	"HOTP": [],
	"PASS": [{
		"Name": "Amazon",
		"Login": "asdf@asdf.as",
		"Password": "pw"
	}]
}
```

The usecases are rather obvious:
-Useful if Nitrokey breaks
-Gain access to services to make new secrets in the event of loosing the Nitrokey
-Simplify migration to new Nitrokey (an import function would help even more)

**Comment by jans23** [comment]
I see your point. But its a very security feature that OTP secrets can't be exported from a Nitrokey. Instead you can create a manual backup of your OTP secret when configuring OTP entries. Would this be ok?

**Comment by MaVo159** [comment]
Oh. I didn't notice that. Makes sense (although... ...if you use your nitrokey on a compromised machine and open the admin interface, the attacker is probably able to set the OTP on the service side and is definitely able to set it on the nitrokey).
I guess OTP secret export will have to wait until there is a nitrokey with pinpad and display (any plans for that yet?).

It would still be nice to export the list of passwords and the OTP settings with an empty Key field.
Otherwise setting up a new key when the old one is broken will be an absolute pain. Forgetting to set up a key you used to have might lock you out in a situation where you really need it and are not able to fix it.

Also, importing OTP settings is still on the table I guess.

Last idea: Assuming that the OTP secrets are not on the tamper proof component (are they?). There is already a 'Hide secret' checkbox. If that setting would be preserved (and of course impossible to reverse after checking it once and saving) it would be up to the user.

**Comment by jans23** [comment]
Think of an attack scenario where you configure your Nitrokey on a secure computer and where your computer is compromised later (potentially years later). Nitrokey helps in those situations. 

I don't see how export would depend on a PIN pad. Instead preventing exports is a fundamental design decision.

Tthe OTP secrets are in fact on the tamper proof Nitrokey and can't be exported. If you load an OTP configuration the secret can't be loaded and its masking ("hide secret") is more of a GUI design.

**Comment by MaVo159** [comment]
Ok, the secret being on the tamper proof chip makes most of my points irrelevant. I didn't really expect that you would want to turn the UI hide feature into a firmware feature anyway, since not masking the secrets is probably a bad idea for default behavior anyway.

Not that it matters, but with PIN pad and display the scenario you are describing wouldn't be an issue (compromised machine), since you wouldn't confirm the export with your PIN if you didn't want to export. I wrote that assuming the OTP storage wasn't tamper proof, it doesn't make sense anymore.
However, a PIN pad & display would protect against the attack I described in the first post.

Academic discussions aside: I still think, export of all settings except the secrets is a very useful feature, when migrating to a new hardware or firmware. The size of the JSON file would decrease a lot if unused slots and fields with default settings were skipped.

**Comment by jans23** [comment]
Yes, we are discussing a useful backup feature regularly. But I don't see this for OTP. Instead I'm more looking towards U2F for which a single backup during initializing the device may be an option. The protocol implicates that no subsequent backups are necessary (because no subsequent configuration is required).

**Comment by MaVo159** [comment]
Not going to revive this. I just would like to clarify something that might mislead people in the conversation above.
I've been reading a bunch of code and some forum entries over the last couple of days and now suspect that I misunderstood what you mean by saying OTP secrets are stored on tamper proof storage.

I thought that meant the secrets are on the smartcard and can't be read by the firmware. Now I suspect you meant that they are on the microprocessor, but the HID protocol doesn't support retrieving them. Is that correct?

**Comment by jans23** [comment]
Correct.
-- 
Sent from a mobile device.
