### ISSUE TITLE
Can't configure hidden volume

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#95]
System: Ubuntu 16.04, firmware 0.35

Steps:

1. Unlock encrypted volume -> success
2. config / Setup hidden volume
3. Go with default parameters (70 / 90), enter "password" as password, confirm

I receive the message "activate encrypted volume first".

Also when trying to unlock the potentially configured hidden volume, I receive a message that the volume is not active.

**Comment by szszszsz** [comment]
@jans23 Could you respond to these questions:
1. Was the device initialized with `Initialize device` after flashing?
2. If possible, could you check is issue occuring after factory reset? `./nitrokey-app --cmd factoryReset`

**Comment by szszszsz** [comment]
Issue has not occured on my Ubuntu 16.04. I have made factory reset after firmware flashing and then checked your scenario. I will recheck without firmware flashing and publish result.

**Comment by szszszsz** [comment]
It looks like it is not occuring either. Could you possibly missed some step for reproduction? Or maybe it works on my side because of factory reset and I have no option to revert it.

**Comment by jans23** [comment]
It seems that the particular device is broken. It works well with other devices.
