### ISSUE TITLE
Can't unlock password safe

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-app#96]
System: Ubuntu 16.04, firmware 0.35

Steps:

1. Connect device
2. Select "unlock password safe"
3. I receive a message stating that the password safe can't be unlocked.

**Comment by szszszsz** [comment]
(same comment as in #95 )
@jans23 Could you respond to these questions:
1. Was the device initialized with `Initialize device` after flashing?
2. If possible, could you check is issue occuring after factory reset? `./nitrokey-app --cmd factoryReset`

**Comment by szszszsz** [comment]
Ubuntu 16.04, Firmware 0.35, Storage
Compiled with `qmake && make`, g++ 5.3.1
Not reproducing on my side with scenario:
1. Flashing device with production tool
2. Running factory reset with `--cmd factoryReset`
3. Running application with `-d -a`
4. `Initializing device`
5. Skipping SD card initialization and disabling warning
6. Unlocking password safe 
7. Entering two passwords for each kind
8. Checking `Passwords` submenu and testing each position
8. Reinserting device, restarting app and checking all entered passwords from `Passwords` submenu

**Comment by szszszsz** [comment]
@rudbo Could you confirm is factory reset needed or not after device flashing?

**Comment by jans23** [comment]
It seems that the particular device is broken. It works well with other devices.

**Comment by KarmusDK** [comment]
I have the same issue when I type in my user PIN on prompt with my Nitrokey Storage 64GB. I have flashed another firmware and reset the device with the `scd serialno` script with gpg. I have also initialized the card with the Nitrokey App run with admin rights in Windows. When I type `gpg --card-status`, I see the PIN counter as "3 0 3", and I wonder if this is normal. It would be 3 3 3, wouldn't it?

**Comment by szszszsz** [comment]
This is normal, we have only `User` and `Admin` PIN counters - it should be `3 0 3`. 
The issue with Password Safe is probably caused by not generated AES key. Please do so through the Application by selecting either `Initialize device` of if it is not available: `Destroy encrypted data`.

**Comment by KarmusDK** [comment]
Brilliant, you were right!

**Comment by szszszsz** [comment]
You are welcome!
