### ISSUE TITLE
Check feedback for firmware password changing with Nitrokey Storage

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-app#97]
Currently no success or failure message is shown while changing firmware password

**Comment by szszszsz** [comment]
To investigate. I have modified the app, but it looks like it works only on first change (=> first change after factory reset, device reinsertion and application restart are not helping). Later password changes are always reported by device as failed. Could you check @rudbo ?

**Comment by rudbo** [comment]
I can't find the problem with my system: 
Win7, Firmware 0.36, App Mainline
The firmware always change the password an send the correct status

**Comment by szszszsz** [comment]
Thank you for checking!

**Comment by szszszsz** [comment]
@rudbo Unfortunately I can confirm your results only partially. It is working for me as I have described in previous comment (only on first successful change) on both Windows 8.0 (compiled with Qt's mingw 5.3) and Ubuntu 16.04. I was using branch `issue_97_firmware_password_feedback` (the only differences in code with mainline are debug prints and feedback logic).
Furthermore I cannot set update mode with any password (default or just set) after change.

**Comment by szszszsz** [comment]
Merged to master password feedback code without debug code.
